import {test,expect} from '@playwright/test';

test('matching entry links start once, including when previous results exist',async({page})=>{
 const signup=await page.request.post('/api/auth/sign-up/email',{data:{name:'Matching entry',email:'matching-entry@example.test',password:'Test-only-password-483!'}});
 expect(signup.ok()).toBe(true);
 let starts=0;
 page.on('request',r=>{if(r.url().endsWith('/api/matching')&&r.method()==='POST'&&r.postDataJSON().action==='start')starts++;});
 await page.goto('/discover');
 await page.getByRole('link',{name:'Find tenders matching my profile',exact:true}).click();
 await expect(page.getByRole('link',{name:'Complete your company capability profile'})).toBeVisible();
 await expect(page).toHaveURL(/\/discover\?recommended=true$/);
 expect(starts).toBe(0);
 expect((await page.request.post('/api/data',{data:{action:'company',company:{name:'Entry supplier',aiProfile:'Supply laboratory instrumentation and radio frequency measurement systems with installation experience.'}}})).ok()).toBe(true);
 await page.goto('/discover');
 await page.getByRole('link',{name:'Find tenders matching my profile',exact:true}).click();
 await expect(page.getByText('Matching complete. Relevance is separate from eligibility.')).toBeVisible();
 await expect(page.locator('.ai-match-card').first()).toBeVisible();
 expect(starts).toBe(1);
 const first=await (await page.request.get('/api/matching')).json();
 await page.reload();
 await expect(page.locator('.ai-match-card').first()).toBeVisible();
 expect(starts).toBe(1);
 await page.getByRole('link',{name:'Keyword discovery',exact:true}).click();
 await expect(page).toHaveURL(/\/discover$/);
 await page.goBack();
 await expect(page).toHaveURL(/\/discover\?recommended=true$/);
 await expect(page.locator('.ai-match-card').first()).toBeVisible();
 expect(starts).toBe(1);
 await page.goto('/overview');
 await page.getByRole('link',{name:'Find tenders matching my profile',exact:true}).click();
 await expect(page.getByText('Matching complete. Relevance is separate from eligibility.')).toBeVisible();
 expect(starts).toBe(2);
 const second=await (await page.request.get('/api/matching')).json();
 expect(second._id).not.toBe(first._id);
 await page.getByRole('button',{name:'Search again',exact:true}).click();
 await expect(page.getByRole('button',{name:'Search again',exact:true})).toBeEnabled();
 expect(starts).toBe(3);
 expect((await (await page.request.get('/api/matching')).json())._id).not.toBe(second._id);
});
