import {test,expect} from '@playwright/test';
import {MongoClient} from 'mongodb';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
test('public discovery, navigation freshness, saved data, profile search and attachment import',async({page,browser})=>{
 const name=process.env.BIDDESK_TEST_DB;if(!name||!/^biddesk_test_[a-f0-9]{16}$/.test(name))throw Error('Isolated database required');const client=new MongoClient(process.env.MONGODB_URI!);await client.connect();const db=client.db(name);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 const signupBody={name:'TenderHut test',email:'source@example.test',password:'Test-only-password-483!'};let signup=await page.request.post('/api/auth/sign-up/email',{data:signupBody});if(signup.status()===429){await page.waitForTimeout(Math.min(60,Number(signup.headers()['retry-after'])||60)*1000);signup=await page.request.post('/api/auth/sign-up/email',{data:signupBody});}expect(signup.ok(),await signup.text()).toBe(true);
 await page.goto('/discover');await expect(page.locator('tbody tr')).toHaveCount(2);await expect(page.getByRole('link',{name:'Find tenders matching my profile'})).toBeVisible();
 await expect(page.getByText('Results updated')).toBeVisible();await page.getByRole('button',{name:'Save 1000464360',exact:true}).click();await expect(page.getByRole('button',{name:'Unsave 1000464360',exact:true})).toBeVisible();
 const count=await db.collection('testSourceRequests').countDocuments({path:/^\/bids/});await page.clock.install();await page.clock.fastForward(6*60000);expect(await db.collection('testSourceRequests').countDocuments({path:/^\/bids/})).toBe(count);
 await page.reload();await expect(page.locator('tbody tr')).toHaveCount(2);expect(await db.collection('testSourceRequests').countDocuments({path:/^\/bids/})).toBeGreaterThan(count);
 await page.locator('a.tender-title').first().click();await expect(page.getByRole('heading',{level:1})).toContainText('LIASONING');await expect(page.getByRole('link',{name:'Open official tender'})).toHaveAttribute('href',/158898/);
 let detail=await(await page.request.get('/api/data?mode=tender&cached=true&id=th-6732969')).json();const version=detail.tender.currentVersion;
 await page.reload();await expect(page.getByRole('heading',{level:1})).toContainText('LIASONING');detail=await(await page.request.get('/api/data?mode=tender&cached=true&id=th-6732969')).json();expect(detail.tender.currentVersion).toBe(version);expect(detail.versions).toHaveLength(1);
 await page.getByRole('button',{name:'Start preparing this bid'}).click();await expect(page).toHaveURL(/bids\//);
 // Source outage falls back to the exact cached query and does not create a version.
 await db.collection('testSourceControl').insertOne({fail:true});await page.goto('/discover');await expect(page.getByText(/Source unavailable. Showing the last successful response/)).toBeVisible();await page.goto('/tenders/th-6732969');await expect(page.getByText(/Could not refresh the source page/)).toBeVisible();await db.collection('testSourceControl').deleteMany({});
 // Explicit profile retrieval discovers scope outside the retained snapshot catalogue.
 expect(await db.collection('tenders').findOne({id:'th-9000001',identityKind:'legacy'})).toBeNull();
 await page.request.post('/api/data',{data:{action:'company',company:{name:'Software supplier',categories:'software',aiProfile:'We deliver software monitoring and control systems for industrial equipment.'}}});await page.goto('/discover?recommended=true');await page.getByRole('button',{name:'Find tenders matching my profile',exact:true}).click();await expect(page.getByText('Matching complete. Relevance is separate from eligibility.')).toBeVisible();await expect(page.locator('.ai-match-card').first()).toContainText('Software control');expect(await db.collection('testSourceRequests').countDocuments({path:/keyword=software/})).toBeGreaterThan(0);expect(await db.collection('tenders').findOne({id:'th-9000001'})).toBeTruthy();
 // Pairing, real ZIP validation, selected PDF extraction, and grant replay rejection.
 await page.goto('/tenders/th-6732969');await page.getByRole('tab',{name:/documents/}).click();await page.getByRole('button',{name:'Pair attachment extension'}).click();const code=await page.getByLabel('Extension pairing code').inputValue();const grant=JSON.parse(Buffer.from(code,'base64url').toString());
 execFileSync('python3',['-c',"import zipfile\np=b'%PDF-1.4\\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\\n5 0 obj<</Length 72>>stream\\nBT /F1 12 Tf 20 200 Td (Public software control tender test fixture) Tj ET\\nendstream endobj\\ntrailer<</Root 1 0 R>>\\n%%EOF'\nwith zipfile.ZipFile('/tmp/biddesk-test-archive.zip','w',zipfile.ZIP_DEFLATED) as z:\n z.writestr('notice.pdf',p)\n z.writestr('readme.doc',b'non-PDF download only')"]);
 const bytes=readFileSync('/tmp/biddesk-test-archive.zip'),headers={'x-biddesk-transfer':grant.token,'content-type':'application/zip'};const upload=await page.request.post('/api/attachments/transfer',{data:bytes,headers});expect(upload.ok(),await upload.text()).toBe(true);expect((await page.request.post('/api/attachments/transfer',{data:bytes,headers})).status()).toBe(403);await page.getByRole('button',{name:'Review transferred files'}).click();await expect(page.getByText('notice.pdf',{exact:true})).toBeVisible();await expect(page.getByText('readme.doc',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Read PDF for review'}).click();await expect(page.getByRole('heading',{name:'Analyze tender documents'})).toBeVisible();await expect(page.getByLabel('Document to analyze')).toContainText('notice.pdf');
 const archives=await(await page.request.get('/api/attachments?tenderId=th-6732969')).json();const other=await browser.newContext();await other.request.post('http://localhost:3001/api/auth/sign-up/email',{data:{name:'Other attachment user',email:'other-source@example.test',password:'Test-only-password-483!'}});expect((await other.request.get(`http://localhost:3001/api/attachments?archive=${archives[0]._id}&index=0`)).status()).toBe(404);await other.close();expect(errors).toEqual([]);
 }finally{await db.collection('testSourceControl').deleteMany({});await client.close();}
});
