import {test,expect,type APIRequestContext} from '@playwright/test';
import {MongoClient} from 'mongodb';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile);
function pdfBytes(){const content='BT /F1 18 Tf 20 180 Td (Laboratory software evidence) Tj 0 -30 Td (Certificate valid through 2099) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 300] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];for(const [i,obj] of objects.entries()){offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`;}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf);}
async function post(request:APIRequestContext,data:unknown){const r=await request.post('/api/workflow',{data});expect(r.ok(),await r.text()).toBe(true);return r.json();}
async function workflow(request:APIRequestContext,id='th-6732969'){const r=await request.get('/api/workflow?mode=tender&id='+id);expect(r.ok(),await r.text()).toBe(true);return r.json();}
test('readiness, evidence, citation viewing, OCR, saved searches, decisions and isolation',async({page,browser})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const signup=await page.request.post('/api/auth/sign-up/email',{headers:{'x-forwarded-for':'192.0.2.111'},data:{name:'Workflow supplier',email:'workflow@example.test',password:'Test-only-password-483!'}});expect(signup.ok()).toBe(true);
 await page.request.get('/api/data?mode=tenders');const {tender}=await(await page.request.get('/api/data?mode=tender&id=th-6732969')).json();
 expect((await workflow(page.request)).status).toBe('Review incomplete');
 const upload=await page.request.post(`/api/files?name=evidence.pdf&tenderId=${tender.id}&version=${tender.currentVersion}`,{data:pdfBytes(),headers:{'content-type':'application/pdf'}});expect(upload.ok(),await upload.text()).toBe(true);const document=await upload.json();expect(document.fileId).toBeTruthy();
 const file=await page.request.get('/api/files?id='+document.fileId);expect(file.headers()['content-type']).toBe('application/pdf');
 await post(page.request,{action:'evidence.save',value:{title:'Accounts FY26',type:'financial',fileId:document.fileId,period:'FY26',amount:120}});
 const settings=await(await page.request.get('/api/workflow?mode=settings')).json(),evidence=settings.evidence[0];
 const requirement={id:'review-finance',label:'Evidenced turnover',type:'turnover',value:'INR',threshold:100,period:'FY26',clause:'Clause 4.1',page:1,confirmed:true,importance:'mandatory',evidenceIds:[evidence.id]};
 expect((await page.request.post('/api/data',{data:{action:'review',id:tender.id,version:tender.currentVersion,requirements:[requirement],notes:''}})).ok()).toBe(true);
 let w=await workflow(page.request);expect(w.rows[0].rule.outcome).toBe('appears satisfied');
 await post(page.request,{action:'document.review',documentId:document.id,pages:[1],reviewed:true});w=await workflow(page.request);expect(w.coverage.reviewed).toBe(1);
 const first=await post(page.request,{action:'task',tenderId:tender.id,requirementId:requirement.id,inputHash:w.inputHash});await post(page.request,{action:'task',tenderId:tender.id,requirementId:requirement.id,inputHash:w.inputHash});
 const workspace=await(await page.request.get('/api/data')).json();expect(workspace.bids.find((b:{id:string})=>b.id===first.bidId).tasks.filter((t:{requirementId:string})=>t.requirementId===requirement.id)).toHaveLength(1);
 await post(page.request,{action:'judgment',tenderId:tender.id,requirementId:requirement.id,inputHash:w.inputHash,outcome:'supporting evidence',note:'Verified the financial document and period.',evidence:'Accounts FY26, page 1',evidenceIds:[evidence.id]});
 w=await workflow(page.request);await post(page.request,{action:'decision',tenderId:tender.id,inputHash:w.inputHash,value:{choice:'bid',reasons:'Company evidence supports pursuing this tender.',effortHours:12}});
 await post(page.request,{action:'submission',tenderId:tender.id,inputHash:w.inputHash,value:{reference:'PORTAL-123',submittedAt:'2026-09-13',fileId:document.fileId}});
 expect((await workflow(page.request)).records.decisionStale).toBe(false);
 const prepared=(await(await page.request.get('/api/data')).json()).bids.find((b:{id:string})=>b.id===first.bidId);await page.request.post('/api/data',{data:{action:'bid.save',id:prepared.id,bid:{...prepared,tasks:prepared.tasks.map((t:Record<string,unknown>)=>({...t,done:true}))}}});
 await post(page.request,{action:'evidence.save',id:evidence.id,revision:0,value:{...evidence,amount:90}});w=await workflow(page.request);expect(w.rows[0].rule.outcome).toBe('not satisfied');expect(w.rows[0].judgment.stale).toBe(true);expect(w.records.decisionStale).toBe(true);
 await post(page.request,{action:'task',tenderId:tender.id,requirementId:requirement.id,inputHash:w.inputHash});const reopened=(await(await page.request.get('/api/data')).json()).bids.find((b:{id:string})=>b.id===first.bidId);expect(reopened.tasks).toHaveLength(1);expect(reopened.tasks[0]).toMatchObject({done:false,changed:true});
 expect((await page.request.post('/api/workflow',{data:{action:'evidence.save',id:evidence.id,revision:0,value:evidence}})).status()).toBe(409);
 expect((await page.request.post('/api/workflow',{data:{action:'judgment',tenderId:tender.id,requirementId:requirement.id,inputHash:w.inputHash,outcome:'supporting evidence',note:'Attempt to override a failed numeric check.',evidence:'Accounts'}})).status()).toBe(400);
 await post(page.request,{action:'search.save',name:'Software opportunities',filters:{q:'software',sort:'deadline',state:'Maharashtra',favorites:'true'}});
 await page.goto('/discover');await page.getByText('Saved searches',{exact:true}).click();await page.getByRole('link',{name:'Software opportunities'}).click();await expect(page).toHaveURL(/q=software/);await expect(page).toHaveURL(/favorites=true/);
 await page.goto('/tenders/'+tender.id);await page.getByRole('tab',{name:'Documents & review',exact:true}).click();await page.getByLabel('Document to analyze').selectOption(document.id);await page.getByText('Document options',{exact:true}).click();await page.getByRole('button',{name:'Page 1: reviewed',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('canvas')).toBeVisible();await page.getByRole('button',{name:'Close dialog'}).click();
 const ocr=await page.request.post('/api/workflow',{data:{action:'ocr',documentId:document.id,pages:[1]},timeout:90000});expect(ocr.ok(),await ocr.text()).toBe(true);const after=await(await page.request.get('/api/workflow?mode=documents&id='+document.id)).json();expect(after.document.ocr).toBe(true);expect(after.document.pages[0].text.toLowerCase()).toContain('laboratory');expect(after.coverage).toHaveLength(0);
 await page.goto('/bids/'+first.bidId);await page.getByRole('textbox',{name:'Decision reasons',exact:true}).fill('Preserve this decision while saving checklist changes.');await page.getByRole('button',{name:'Add task',exact:true}).click();await expect(page.getByRole('button',{name:'Save decision & submission'})).toBeDisabled();await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('textbox',{name:'Decision reasons',exact:true})).toHaveValue('Preserve this decision while saving checklist changes.');await page.getByRole('button',{name:'Save decision & submission'}).click();await expect(page.getByText('Decision and submission records saved',{exact:true})).toBeVisible();expect((await workflow(page.request)).records.decision.reasons).toBe('Preserve this decision while saving checklist changes.');
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.goto('/bids/'+first.bidId);await expect(page.getByRole('heading',{name:'Bid readiness'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 const other=await browser.newContext({baseURL:'http://localhost:3001'});await other.request.post('/api/auth/sign-up/email',{headers:{'x-forwarded-for':'192.0.2.112'},data:{name:'Other workflow',email:'workflow-other@example.test',password:'Test-only-password-483!'}});expect((await other.request.get('/api/files?id='+document.fileId)).status()).toBe(404);expect((await other.request.get('/api/workflow?mode=documents&id='+document.id)).status()).toBe(404);expect((await(await other.request.get('/api/workflow?mode=settings')).json()).evidence).toHaveLength(0);await other.close();
 await post(page.request,{action:'document.delete',documentId:document.id});expect((await page.request.get('/api/files?id='+document.fileId)).status()).toBe(404);expect((await workflow(page.request)).status).toBe('Review incomplete');expect(errors).toEqual([]);
});
test('monitoring deduplicates local delivery and cancels obsolete reminders',async({request})=>{
 const signup=await request.post('/api/auth/sign-up/email',{headers:{'x-forwarded-for':'192.0.2.113'},data:{name:'Reminder supplier',email:'reminders@example.test',password:'Test-only-password-483!'}});expect(signup.ok()).toBe(true);const ownerId=(await signup.json()).user.id;
 await request.get('/api/data?mode=tenders');await request.get('/api/data?mode=tender&id=th-6732969');const result=await request.post('/api/data',{data:{action:'bid.create',id:'th-6732969'}}),{bid}=await result.json();
 const due=new Date().toISOString().slice(0,10);await request.post('/api/data',{data:{action:'bid.save',id:bid.id,bid:{...bid,tasks:[{id:'due-task',title:'Prepare evidence today',done:false,dueAt:due,assignee:'',notes:'',requirementId:'',changed:false}]}}});
 await post(request,{action:'watch',value:{enabled:true,saved:false,bids:true,email:true,days:[0]}});
 const name=process.env.BIDDESK_TEST_DB!;if(!/^biddesk_test_[a-f0-9]{16}$/.test(name))throw new Error('Isolated DB required');
 const run=()=>exec(process.execPath,['node_modules/tsx/dist/cli.mjs','scripts/monitor.ts'],{env:{...process.env,MONGODB_DB:name,BIDDESK_SOURCE_TEST_FIXTURES:'1',BIDDESK_MAIL_MODE:'sink',BETTER_AUTH_URL:'http://localhost:3001'},timeout:90000});await run();await run();
 const client=new MongoClient(process.env.MONGODB_URI!);try{await client.connect();const db=client.db(name);expect(await db.collection('deliveryOutbox').countDocuments({ownerId,sourceKey:{$regex:'^task:'}})).toBe(1);expect((await db.collection('deliveryOutbox').findOne({ownerId,sourceKey:{$regex:'^task:'}}))?.status).toBe('local sink delivered');expect(await db.collection('notifications').countDocuments({ownerId,id:{$regex:'^reminder:'}})).toBe(1);
 await db.collection('deliveryOutbox').insertOne({id:'obsolete-test',ownerId,tenderId:'th-6732969',status:'pending',nextAt:new Date(),createdAt:new Date().toISOString(),sourceKey:'obsolete',attempts:0});await post(request,{action:'watch',value:{enabled:false}});await run();expect((await db.collection('deliveryOutbox').findOne({id:'obsolete-test'}))?.status).toBe('cancelled');
 const calendar=await request.get('/api/calendar');expect(calendar.ok()).toBe(true);expect(await calendar.text()).toContain('DTSTART;VALUE=DATE:'+due.replaceAll('-',''));
 }finally{await client.close();}
});
test('remaining-page analysis resumes after a failed batch without repeating completed pages',async({page})=>{
 await page.request.post('/api/auth/sign-up/email',{headers:{'x-forwarded-for':'192.0.2.114'},data:{name:'Coverage supplier',email:'coverage@example.test',password:'Test-only-password-483!'}});await page.request.get('/api/data?mode=tenders');const {tender}=await(await page.request.get('/api/data?mode=tender&id=th-6732969')).json();
 const pages=Array.from({length:35},(_,i)=>({page:i+1,text:`Page ${i+1}: Supply laboratory instrumentation and software systems. Documentary evidence requires individual human review.`}));
 const attached=await page.request.post('/api/ai',{data:{action:'attach',tenderId:tender.id,version:tender.currentVersion,document:{name:'Thirty-five page notice',pages}}});expect(attached.ok()).toBe(true);const d=await attached.json();
 let fail=true;const starts:number[]=[];await page.route('**/api/ai',async route=>{const b=route.request().postDataJSON();if(b.action==='extract'){starts.push(b.pages[0]);if(fail&&b.pages[0]===31){await route.fulfill({status:503,json:{error:'Temporary analysis failure'}});return;}}await route.continue();});
 await page.goto('/tenders/'+tender.id);await page.getByRole('tab',{name:'Documents & review',exact:true}).click();await page.getByLabel('Document to analyze').selectOption(d.id);await page.getByText('Document options',{exact:true}).click();await page.getByRole('button',{name:'Analyze remaining pages',exact:true}).click();await expect(page.getByText('Analysis paused. Completed sections are retained.',{exact:true})).toBeVisible();let coverage=await(await page.request.get('/api/workflow?mode=documents&id='+d.id)).json();expect(coverage.coverage.filter((c:{analyzed?:boolean})=>c.analyzed)).toHaveLength(30);expect(coverage.coverage.some((c:{reviewed?:boolean})=>c.reviewed)).toBe(false);
 fail=false;await page.getByRole('button',{name:'Analyze remaining pages',exact:true}).click();await expect(page.getByText('Analysis complete. Private findings saved.',{exact:true})).toBeVisible();coverage=await(await page.request.get('/api/workflow?mode=documents&id='+d.id)).json();expect(coverage.coverage.filter((c:{analyzed?:boolean})=>c.analyzed)).toHaveLength(35);expect(starts.filter(p=>p===1)).toHaveLength(1);
});
test('local OCR reads a raster scan with table numbers',async({request})=>{
 const signup=await request.post('/api/auth/sign-up/email',{headers:{'x-forwarded-for':'192.0.2.115'},data:{name:'Scan supplier',email:'scans@example.test',password:'Test-only-password-483!'}});expect(signup.ok(),await signup.text()).toBe(true);await request.get('/api/data?mode=tenders');const {tender}=await(await request.get('/api/data?mode=tender&id=th-6732969')).json();const {scannedPdf}=await import('../fixtures/scanned-pdf');
 const upload=await request.post(`/api/files?name=scanned-table.pdf&tenderId=${tender.id}&version=${tender.currentVersion}`,{data:scannedPdf(),headers:{'content-type':'application/pdf'}});expect(upload.ok(),await upload.text()).toBe(true);const d=await upload.json();expect(d.pages[0].text.trim()).toBe('');
 await post(request,{action:'ocr',documentId:d.id,pages:[1]});const result=await(await request.get('/api/workflow?mode=documents&id='+d.id)).json();const text=result.document.pages[0].text.toLowerCase();for(const word of ['laboratory','12345','120','25'])expect(text).toContain(word);expect(result.document.warnings.join(' ')).toContain('OCR confidence');expect(result.coverage).toHaveLength(0);
});
