import { test, expect, type APIRequestContext } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { tenderSchema, requirementSchema, type Bid } from "../../src/lib/schemas";
async function post(request:APIRequestContext,data:unknown){const r=await request.post("/api/data",{data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();}
test("real snapshot browser journey and private import/amendment isolation",async({page,browser})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto("/sign-up");
 await page.getByLabel("Full name").fill("Verification Workspace");await page.getByLabel("Email address").fill("first@example.test");await page.getByLabel("Password",{exact:true}).fill("Test-only-password-483!");await page.getByRole("button",{name:"Create workspace"}).click();
 await expect(page.getByRole("heading",{level:1})).toBeVisible();await expect(page).toHaveURL(/overview/);
 await page.getByRole("link",{name:"Discover tenders",exact:true}).click();
 await expect(page.locator("tbody tr")).toHaveCount(15);await page.screenshot({path:".local/discover-desktop.png",fullPage:true});
 const firstSave=page.getByRole("button",{name:/^Save /}).first();await firstSave.click();await expect(page.getByRole("button",{name:/^Unsave /}).first()).toBeVisible();await page.reload();await expect(page.getByRole("button",{name:/^Unsave /}).first()).toBeVisible();
 await page.getByRole("checkbox",{name:/^Compare /}).nth(0).check();await page.getByRole("checkbox",{name:/^Compare /}).nth(1).check();await page.getByRole("link",{name:"Compare tenders →"}).click();await expect(page.locator(".comparison-table thead th")).toHaveCount(3);
 await page.goto("/discover");await page.getByLabel("Search tenders",{exact:true}).fill("PRL");await page.getByRole("button",{name:"Search",exact:true}).click();await expect(page).toHaveURL(/q=PRL/);await expect(page.locator("tbody tr").first()).toContainText("PRL");
 const exported=await page.request.get("/api/data?mode=export&q=PRL");expect(exported.ok()).toBeTruthy();expect(await exported.text()).toContain("PRL");expect(exported.headers()["cache-control"]).toContain("no-store");
 await page.goto("/imports");await page.getByRole("button",{name:/Import a spreadsheet/}).click();
 await page.getByLabel("Tender CSV").setInputFiles({name:"import.csv",mimeType:"text/csv",buffer:Buffer.from('title,reference,value\nPrivate test CSV,TEST-CSV,42\nInvalid test row,INVALID,-1')});await expect(page.getByText("Ready",{exact:true})).toBeVisible();await expect(page.getByText(/1 valid rows will be imported/)).toBeVisible();await page.getByRole("checkbox",{name:/I reviewed these details/}).check();await page.getByRole("button",{name:"Import reviewed records"}).click();await expect(page.getByRole("heading",{name:"Import results"})).toBeVisible();await expect(page.getByText("imported",{exact:true})).toBeVisible();
 // Actual public notice with an isolated test requirement: never seeds demo data.
 const snapshot=JSON.parse(await readFile("data/public/isro-tenders.json","utf8"));
 const rule=requirementSchema.parse({id:"turnover-test",label:"Test-only minimum turnover",type:"turnover",threshold:100,value:"INR",period:"FY 2025-26",clause:"Test fixture",page:1,confirmed:true});
 const input=tenderSchema.parse({...snapshot.records[0],reference:"TEST-AMEND",source:"Isolated verification fixture",title:"Private amendment verification",requirements:[rule]});
 const imported=await post(page.request,{action:"import",records:[input]});const id=imported.results[0].id;expect(id).toBeTruthy();
 const again=await post(page.request,{action:"import",records:[input]});expect(again.results[0].result).toBe("unchanged");
 await post(page.request,{action:"company",company:{name:"Verification Company",turnover:150,turnoverPeriod:rule.period,turnoverEvidence:"Test accounts"}});
 await page.goto(`/tenders/${id}`);await page.getByRole("tab",{name:"eligibility"}).click();await expect(page.getByText("appears satisfied",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Start preparing this bid"}).click();await expect(page).toHaveURL(/bids\//);await page.getByLabel("Complete task 1").check();await page.getByLabel("Evidence / task notes").fill("Evidence retained after amendment");await page.getByRole("button",{name:"Save changes"}).click();await expect(page.getByText("Bid preparation saved")).toBeVisible();await page.reload();await expect(page.getByLabel("Complete task 1")).toBeChecked();
 const detail=(await (await page.request.get(`/api/data?mode=tender&id=${id}`)).json());const originalBid:Bid=detail.bid;
 const changed={...input,closesAt:"2099-10-01",requirements:[{...rule,threshold:200}]};const amended=await post(page.request,{action:"import",existingId:id,records:[changed]});expect(amended.results[0].result).toBe("updated");
 let current=await (await page.request.get(`/api/data?mode=tender&id=${id}`)).json();expect(current.versions).toHaveLength(2);expect(current.bid.tasks[0]).toMatchObject({done:false,changed:true,notes:"Evidence retained after amendment"});
 await post(page.request,{action:"import",existingId:id,records:[changed]});current=await (await page.request.get(`/api/data?mode=tender&id=${id}`)).json();expect(current.versions).toHaveLength(2);expect(current.bid.events).toHaveLength(1);
 expect((await page.request.post("/api/data",{data:{action:"bid.save",id:originalBid.id,bid:originalBid}})).status()).toBe(409);
 await post(page.request,{action:"import",existingId:id,records:[input]});current=await (await page.request.get(`/api/data?mode=tender&id=${id}`)).json();expect(current.versions).toHaveLength(3);expect(current.bid.events).toHaveLength(2);
 const other=await browser.newContext({baseURL:"http://localhost:3001"});const signup=await other.request.post("/api/auth/sign-up/email",{data:{name:"Other user",email:"second@example.test",password:"Test-only-password-483!"}});expect(signup.ok(),await signup.text()).toBeTruthy();expect((await other.request.get(`/api/data?mode=tender&id=${id}`)).status()).toBe(404);const foreignImport=await post(other.request,{action:"import",existingId:id,records:[input]});expect(foreignImport.results[0].result).toBe("rejected");expect(await (await other.request.get("/api/data?mode=export")).text()).not.toContain("Private amendment verification");await other.close();
 await page.goto("/calendar");await expect(page.getByRole("heading",{level:1})).toBeVisible();await page.goto("/results");await expect(page.getByRole("heading",{level:1})).toBeVisible();await page.getByRole("button",{name:"Import award",exact:true}).click();await page.getByLabel("Contract title").fill("Test-only award fixture");await page.getByLabel("Official reference",{exact:true}).fill("AWARD-TEST");await page.getByLabel("Official source URL",{exact:true}).fill("https://example.com/test-only-award");await page.getByRole("button",{name:"Save award record"}).click();await expect(page.getByText("Test-only award fixture",{exact:true})).toBeVisible();
 await page.goto("/company");await expect(page.getByLabel("Company name",{exact:true})).toHaveValue("Verification Company");await page.getByLabel("Company name",{exact:true}).fill("Verified browser company");await page.getByRole("button",{name:"Save company profile"}).click();await expect(page.getByText("Company profile saved")).toBeVisible();await page.reload();await expect(page.getByLabel("Company name",{exact:true})).toHaveValue("Verified browser company");
 const workspace=await (await page.request.get("/api/data")).json();expect(workspace.notifications).toHaveLength(2);await post(page.request,{action:"notifications.read"});expect((await (await page.request.get("/api/data")).json()).notifications.every((n:{read:boolean})=>n.read)).toBeTruthy();
 await page.setViewportSize({width:390,height:844});await page.goto("/overview");await expect(page.getByRole("button",{name:"Open navigation"})).toBeVisible();await expect(page.getByRole("heading",{level:1})).toBeVisible();await page.screenshot({path:".local/overview-mobile.png",fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.getByRole("button",{name:"Open navigation"}).click();await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/sign-in/);expect((await page.request.get("/api/data")).status()).toBe(401);expect(errors).toEqual([]);
});
test("real PDF browser extraction",async({page})=>{
 test.skip(!process.env.BIDDESK_TEST_PDF,"Set BIDDESK_TEST_PDF to an official text PDF for the source rehearsal");
 await page.goto("/sign-in");await page.getByLabel("Email address").fill("first@example.test");await page.getByLabel("Password",{exact:true}).fill("Test-only-password-483!");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/overview/);
 await page.goto("/imports");await page.getByRole("button",{name:/Read a PDF/}).click();await page.getByLabel("Tender PDF").setInputFiles(process.env.BIDDESK_TEST_PDF!);await expect(page.getByText(/pages extracted. Review/)).toBeVisible({timeout:60000});
 await page.getByLabel("Tender title",{exact:false}).fill("Official document extraction rehearsal");await page.getByLabel("Official reference",{exact:false}).fill("PDF-REHEARSAL");await page.getByRole("checkbox",{name:/I reviewed these details/}).check();await page.getByRole("button",{name:"Import reviewed records"}).click();await expect(page.getByText("imported",{exact:true})).toBeVisible();await page.getByRole("link",{name:/Open tender/}).click();await page.getByRole("tab",{name:/documents/}).click();await expect(page.getByText(/extracted pages · original binary/)).toBeVisible();
});
