"use client";
import {useState} from "react";
import type {TenderInput} from "@/lib/schemas";
import {requirementSchema} from "@/lib/schemas";
import type {Draft,SourceDocument} from "@/lib/ai/contracts";
import {AIButton,aiRequest,useAIAction} from "./ai-common";
import {DraftReview} from "./ai-documents";
import {SectionHeader} from "./ui";
export function AIImport({draft,onChange}:{draft:TenderInput;onChange:(draft:TenderInput)=>void}){const [result,setResult]=useState<Draft|null>(null),[inputRevision,setInputRevision]=useState(""),[docId,setDocId]=useState("");const {busy,error,run}=useAIAction();const index=draft.documents.findIndex(d=>d.pages.some(p=>p.text.trim().length>=30));if(index<0)return null;const document=draft.documents[index];return <section className="panel form-panel ai-panel mt"><SectionHeader title="Fill this import from its document"/><p className="muted">Gemini can suggest form fields and requirements from the first 30 readable pages. Review before applying; manually entered values are preserved unless you explicitly select a replacement.</p><AIButton disabled={busy} onClick={()=>run(async()=>{const revision=JSON.stringify(draft);setInputRevision(revision);const d=await aiRequest<SourceDocument>({action:"attach",document:{name:document.name,pages:document.pages}});setDocId(d.id);const pages=document.pages.filter(p=>p.text.trim().length>=30).slice(0,30).map(p=>p.page);let total=1;for(let chunkIndex=0;chunkIndex<total;chunkIndex++){const r=await aiRequest<{draft:Draft;totalChunks:number}>({action:"extract",documentId:d.id,pages,chunkIndex});total=r.totalChunks;setResult(r.draft);}})}>{busy?"Analyzing document…":"Suggest import fields"}</AIButton>{error&&<p className="error" role="alert">{error}</p>}{result&&(inputRevision!==JSON.stringify(draft)?<p className="info-box">The import form changed. Analyze again before applying these suggestions.</p>:<DraftReview draft={result} onManualApply={(fields,requirements)=>{const next={...draft,documents:draft.documents.map((d,i)=>i===index?{...d,analysisDocumentId:docId}:d)};for(const f of fields){Object.assign(next,{[f.key]:["value","emd","fee"].includes(f.key)?Number(f.value):f.value});}next.requirements=[...draft.requirements,...requirements.map(r=>requirementSchema.parse({...r,id:crypto.randomUUID(),confirmed:false,origin:"ai-assisted",clause:document.name,page:r.citations[0].page}))];onChange(next);setResult(null);}}/>)}</section>;}
