"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {Run} from '@/lib/tenderhut/matching';
import {formatDate} from '@/lib/domain';
import {useWorkspace} from './context';
export function AIMatching(){const {data}=useWorkspace();const [run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');const stop=useRef(false);
 useEffect(()=>{fetch('/api/matching').then(r=>r.ok?r.json():null).then(setRun).catch(()=>{});},[]);
 async function request(action:string,runId?:string){const res=await fetch('/api/matching',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,runId})});const v=await res.json();if(!res.ok)throw new Error(v.error);setRun(v);return v as Run;}
 async function execute(resume=false){setBusy(true);setError('');stop.current=false;try{setProgress('Searching source portal using your company profile…');let r=resume&&run?run:await request('start');while(r.prepared<r.items.length&&!stop.current){setProgress(`Reviewing opportunity ${r.prepared+1} of ${r.items.length}…`);try{r=await request('prepare',r._id);}catch(e){setError(String(e));break;}}if(!stop.current){setProgress('Ranking retrieved opportunities and explaining the strongest matches…');r=await request('finish',r._id);setRun(r);setProgress('Matching complete. Relevance is separate from eligibility.');}else setProgress('Stopped. Retrieved results and completed AI work are retained.');}catch(e){setError(e instanceof Error?e.message:'Matching unavailable');}finally{setBusy(false);}}
 return <section className="panel form-panel ai-panel mt"><h2>Find tenders matching my profile</h2><p className="muted">Search current Indian notices using your offerings, then compare their published scope with your capabilities. Each search reviews a limited selection of notices; it does not cover every available tender.</p>{data.company.aiProfile.trim().length<30?<p className="info-box"><Link href="/company">Complete your company capability profile</Link> to start matching.</p>:<><div className="row wrap"><button className="button" disabled={busy} onClick={()=>execute()}>Find tenders matching my profile</button>{run&&!run.finished&&<button className="button secondary" disabled={busy} onClick={()=>execute(true)}>Resume analysis</button>}{busy&&<button className="button secondary" onClick={()=>{stop.current=true;}}>Stop after this request</button>}</div></>}{progress&&<p role="status" className="info-box">{progress}</p>}{error&&<p role="alert" className="error">{error}</p>}{run&&<>{run.stale&&<p className="info-box">Your profile or a tender changed. These are previous results; run matching again before relying on them.</p>}<p className="muted">Best matches among {run.retrieved} retrieved results · {run.prepared} reviewed for relevance · {formatDate(run.generatedAt,true)}</p><p className="small-text">Searches: {run.queries.join(' · ')}</p>{run.warnings.map((w,i)=><p key={i} className="info-box">{w}</p>)}{!run.items.length&&<p>No opportunities returned. Refine the offerings in your profile or use keyword discovery.</p>}{run.items.map(t=><article className="ai-match-card" key={t.id}><small>#{t.rank} · {t.quality}</small><h3><Link href={`/tenders/${t.id}`}>{t.title}</Link></h3>{t.explanation?<><p><strong>Why it matches:</strong> {t.explanation.reason}</p><p><strong>Still to check:</strong> {t.explanation.gap}</p><details><summary>Notice excerpt</summary><blockquote>{t.explanation.quote}</blockquote></details></>:<p className="muted">No AI explanation available. Review the published scope.</p>}</article>)}</>}</section>;
}
