"use client";
import {useEffect,useState,useRef} from "react";
import Link from "next/link";
import {Sparkles,ArrowUpRight} from "lucide-react";
import {AIConsent,AIButton,aiRead,aiRequest,useAIAction} from "./ai-common";
import {Badge,SectionHeader} from "./ui";
import {useWorkspace} from "./context";
import {formatDate} from "@/lib/domain";
type Matches={stale?:boolean;generatedAt:string;coverage:{visible:number;filtered:number;described:number;ranked:number};items:{id:string;title:string;rank:number;quality:string;sourceUrl:string;checkedAt:string;explanation:{reason:string;gap:string;quote:string}|null}[]};
type Status={config:{configured:boolean;enabled:boolean;generationModel:string;embeddingModel:string;generationLimit:number};candidates:{id:string;title:string}[];coverage:{visible:number;described:number};matches:Matches|null};
export function AIMatching(){const {data}=useWorkspace(),[status,setStatus]=useState<Status|null>(null),[approved,setApproved]=useState(false),[progress,setProgress]=useState(""),[state,setState]=useState(""),[category,setCategory]=useState("");const {busy,error,run}=useAIAction(),cancel=useRef(false);useEffect(()=>{aiRead<Status>().then(setStatus).catch(()=>{});},[]);async function prepare(){cancel.current=false;await run(async()=>{const s=await aiRead<Status>();setStatus(s);for(let i=0;i<s.candidates.length;i++){if(cancel.current){setProgress("Preparation stopped. Completed embeddings are cached.");return;}setProgress(`Preparing ${i+1} of ${s.candidates.length} described notices…`);await aiRequest({action:"embed",tenderId:s.candidates[i].id,consent:approved});}setProgress("Ranking scope relevance and explaining the strongest matches…");const matches=await aiRequest<Matches>({action:"matches",filters:{state:state||undefined,category:category||undefined},explain:true,consent:approved});setStatus({...s,matches});setProgress("Recommendations ready. Relevance and eligibility are assessed separately.");});}
 const options=(key:"state"|"category")=>[...new Set(data.tenders.map(t=>t[key]).filter(Boolean))].sort();
 return <section className="panel form-panel ai-panel mt"><SectionHeader title="Recommended for you"><Sparkles size={22}/></SectionHeader><p className="muted">Semantic matching compares your <Link href="/company">AI-shareable capability profile</Link> with actual tender scope. Reference-only notices remain in ordinary discovery.</p>{status&&!status.config.configured&&<p className="info-box">Gemini is not configured. Add the server API key to enable semantic recommendations; keyword discovery remains available.</p>}<p className="small-text">Coverage: {status?.coverage.described??"…"} described notices out of {status?.coverage.visible??data.tenders.length} visible records. Snapshot source dates still apply.</p><div className="form-grid"><label>Recommendation state<select value={state} onChange={e=>setState(e.target.value)}><option value="">All states</option>{options("state").map(s=><option key={s}>{s}</option>)}</select></label><label>Recommendation category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{options("category").map(s=><option key={s}>{s}</option>)}</select></label></div><AIConsent value={approved} onChange={setApproved}/><div className="row wrap"><AIButton disabled={busy||!approved||!status?.config.configured} onClick={prepare}>{busy?"Preparing recommendations…":"Find semantic matches"}</AIButton>{busy&&<button className="button secondary" type="button" onClick={()=>{cancel.current=true;}}>Stop after current request</button>}</div>{progress&&<p className="info-box mt" role="status">{progress}</p>}{error&&<p className="error" role="alert">{error}</p>}{status?.matches&&<div className="mt">{status.matches.stale&&<p className="error">The profile or catalogue changed. Refresh these recommendations.</p>}<p className="muted small-text">{status.matches.coverage.ranked} described records ranked · {formatDate(status.matches.generatedAt,true)} · the last run’s filters apply.</p>{status.matches.items.length?status.matches.items.map(t=><article className="ai-match-card" key={t.id}><div className="row between"><Badge tone="blue">Relevance rank {t.rank}</Badge><Badge>{t.quality}</Badge></div><h3><Link href={`/tenders/${t.id}`}>{t.title} <ArrowUpRight size={16}/></Link></h3>{t.explanation?<><p><strong>Why it matches:</strong> {t.explanation.reason}</p><p className="muted"><strong>Still to check:</strong> {t.explanation.gap}</p><details><summary>Supporting scope excerpt</summary><blockquote>{t.explanation.quote}</blockquote></details></>:<p className="muted">Ranked by semantic similarity. A grounded explanation is not available.</p>}<small>Source checked {formatDate(t.checkedAt,true)} · eligibility still requires review</small></article>):<p className="info-box">No described notices matched these filters. Use ordinary discovery or analyze additional documents.</p>}</div>}</section>;
}
