'use client';
import {useEffect,useState,useCallback} from 'react';
import {Download,Copy,Link2,FileText} from 'lucide-react';
import type {Archive} from '@/lib/attachments/store';
import {AsyncButton,ErrorState,Loading} from './ui';
import {formatDate} from '@/lib/domain';
async function readArchives(tenderId:string,signal?:AbortSignal):Promise<Archive[]>{const r=await fetch("/api/attachments?tenderId="+encodeURIComponent(tenderId),{signal}),v=await r.json();if(!r.ok||!Array.isArray(v))throw new Error(v.error||"Could not load transferred files.");return v;}
export function Attachments({tenderId,onRead}:{tenderId:string;onRead:()=>void}){
 const [archives,setArchives]=useState<Archive[]>([]),[code,setCode]=useState(''),[error,setError]=useState(''),[listError,setListError]=useState(''),[loading,setLoading]=useState(true),[status,setStatus]=useState('');
 const load=useCallback(async()=>{try{const v=await readArchives(tenderId);setArchives(v);setListError('');return true;}catch(e){setListError(e instanceof Error?e.message:'Could not load transferred files.');return false;}finally{setLoading(false);}},[tenderId]);
 useEffect(()=>{const ac=new AbortController();readArchives(tenderId,ac.signal).then(v=>{if(!ac.signal.aborted){setArchives(v);setListError("");}}).catch(e=>{if(!ac.signal.aborted)setListError(e.message);}).finally(()=>{if(!ac.signal.aborted)setLoading(false);});return()=>ac.abort();},[tenderId]);
 async function action(body:unknown){setError('');setStatus('');try{const r=await fetch('/api/attachments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw new Error(v.error);return v;}catch(e){setError(e instanceof Error?e.message:'Attachment action failed. Try again.');}}
 return <div className="attachment-transfer"><p className="muted">Transfer files from a signed-in source portal using the Firefox extension. Your portal credentials stay in your browser.</p><details><summary>Set up the Firefox extension</summary><p>Download and extract the <a className="text-button" href="/biddesk-attachment-extension.zip" download>extension ZIP</a>. In Firefox, open <code>about:debugging#/runtime/this-firefox</code>, choose Load Temporary Add-on, and select its manifest.json. Sign in to the source portal in another tab. Temporary installation lasts until Firefox restarts.</p></details>
 <div className="page-actions mt"><AsyncButton pending="Creating pairing code…" onClick={async()=>{const v=await action({action:'pair',tenderId});if(v)setCode(v.code);}}><Link2 size={18}/>Pair attachment extension</AsyncButton></div>
 {code&&<div className="info-box"><p>Paste this one-use code into the extension. It expires after 10 minutes.</p><textarea readOnly rows={3} value={code} aria-label="Extension pairing code"/><div className="page-actions mt"><AsyncButton pending="Copying…" onClick={async()=>{try{await navigator.clipboard.writeText(code);setStatus('Pairing code copied.');}catch{setError('Could not copy the code. Select and copy it from the field above.');}}}><Copy size={18}/>Copy pairing code</AsyncButton><AsyncButton pending="Checking transferred files…" onClick={async()=>{setLoading(true);if(await load()){setCode('');setStatus('Transferred files refreshed.');}}}>Review transferred files</AsyncButton></div></div>}
 {loading&&<Loading compact>Loading transferred files…</Loading>}{listError&&<ErrorState message={listError} onRetry={()=>{setLoading(true);void load();}}/>}{error&&<ErrorState message={error}/>} {status&&<p role="status" className="info-box">{status}</p>}
 {!loading&&!listError&&!archives.length&&<p className="muted mt">No transferred files yet. After transferring, select “Review transferred files”.</p>}
 {archives.map(a=><div className="mt" key={a._id}><h4>Transferred {formatDate(a.at,true)}</h4>{a.entries.map((e,i)=><div className="document-card mt" key={i}><strong>{e.name}</strong><p>{(e.size/1024).toFixed(0)} KB · {e.pdf?'PDF':'Download only'}</p><div className="page-actions"><a className="button secondary" href={`/api/attachments?archive=${a._id}&index=${i}`}><Download size={18}/>Download file</a>{e.pdf&&<AsyncButton className="button" pending="Reading PDF…" onClick={async()=>{if(await action({action:'read',archive:a._id,index:i})){onRead();setStatus('PDF ready. Select it in the document review below.');}}}><FileText size={18}/>Read PDF for review</AsyncButton>}</div></div>)}</div>)}</div>;
}
