"use client";
import { ReadinessPanel, BidRecords, OutcomeSummary } from "./workflow";
import { useState,useEffect } from "react";
import Link from "next/link";
import { ArrowRight,Plus,Download,Trash2,ArrowLeft,RefreshCw } from "lucide-react";
import { useWorkspace,useAction } from "./context";
import { stages,type Bid,type Task } from "@/lib/schemas";
import { csv,formatDate } from "@/lib/domain";
import { Badge,Empty,SectionHeader,download,AsyncButton,SaveBar,useUnsavedChanges } from "./ui";
export function BidsView(){const {data}=useWorkspace();const [filter,setFilter]=useState(""),[shown,setShown]=useState(20);const bids=data.bids.filter(b=>!filter||b.stage===filter);return <><div className="page-heading"><div><h1>My bids</h1><p>Your preparation, decisions, and next actions in one place.</p></div><Link href="/discover" className="button"><Plus size={16}/>Find a tender</Link></div><OutcomeSummary/><div className="pipeline-stages"><button aria-pressed={!filter} className={!filter?"active":""} onClick={()=>setFilter("")}>All bids <span>{data.bids.length}</span></button>{stages.map(s=><button aria-pressed={filter===s} className={filter===s?"active":""} key={s} onClick={()=>setFilter(s)}>{s.replace("-"," ")}<span>{data.bids.filter(b=>b.stage===s).length}</span></button>)}</div>{!bids.length?<div className="panel"><Empty title={filter?"No bids in this stage":"Your next bid starts here"}><p>Open a tender and select “Start preparing this bid” to create a workspace.</p><Link className="button" href="/discover">Discover tenders <ArrowRight size={16}/></Link></Empty></div>:<div className="bid-grid">{bids.slice(0,shown).map(b=>{const done=b.tasks.filter(t=>t.done).length;return <div className="bid-card" key={b.id}><div className="row between"><Badge tone={b.stage==="won"?"green":"blue"}>{b.stage}</Badge><ArrowRight size={18}/></div><h3><Link href={`/bids/${b.id}`}>{b.title}</Link></h3><small>Deadline {formatDate(data.tenders.find(t=>t.id===b.tenderId)?.closesAt,true)}</small><div className="progress-track"><div style={{width:`${b.tasks.length?done/b.tasks.length*100:0}%`}}/></div><div className="row between"><span>{done} of {b.tasks.length} tasks complete</span>{b.tasks.some(t=>t.changed)&&<Badge tone="amber">Changes to review</Badge>}</div><ReadinessPanel tenderId={b.tenderId} compact/></div>;})}{bids.length>shown&&<button className="button secondary" onClick={()=>setShown(n=>n+20)}>Load more bids</button>}</div>}</>;}
export function BidDetail({id}:{id:string}){const {data,notify}=useWorkspace();const [checklistDirty,setChecklistDirty]=useState(false);const original=data.bids.find(b=>b.id===id);return original?<><BidEditor key={`${id}:${original.revision}`} original={original} onDirtyChange={setChecklistDirty}/><BidRecords tenderId={original.tenderId} disabled={checklistDirty}/></>:<div className="panel"><Empty title="Bid not found"><Link href="/bids" onClick={()=>notify("Only your own bids are accessible.")}>Back to my bids</Link></Empty></div>;}
function BidEditor({original,onDirtyChange}:{original:Bid;onDirtyChange:(dirty:boolean)=>void}){
 const {data}=useWorkspace(),act=useAction();const [bid,setBid]=useState(original),[busy,setBusy]=useState(false);
 const tender=data.tenders.find(t=>t.id===bid.tenderId),dirty=JSON.stringify(bid)!==JSON.stringify(original);useUnsavedChanges(dirty);useEffect(()=>{onDirtyChange(dirty);},[dirty,onDirtyChange]);
 const edit=(id:string,patch:Partial<Task>)=>setBid(b=>({...b,tasks:b.tasks.map(t=>t.id===id?{...t,...patch}:t)}));
 async function save(){if(busy)return;setBusy(true);try{await act({action:"bid.save",id:bid.id,bid},"Bid preparation saved");}finally{setBusy(false);}}
 return <><Link className="back-link" href="/bids"><ArrowLeft size={18}/>My bids</Link><div className="page-heading"><div><h1 className="long-title">{bid.title}</h1><p>{tender?.authority || "Your private preparation workspace"}</p></div><div className="page-actions"><Link href={`/tenders/${bid.tenderId}`} className="button secondary">Tender details <ArrowRight size={18}/></Link></div></div>
 <fieldset className="editor-fields" disabled={busy}><div className="panel bid-toolbar"><label>Pipeline stage<select value={bid.stage} onChange={e=>setBid({...bid,stage:e.target.value as Bid["stage"]})}>{stages.map(s=><option value={s} key={s}>{s.replaceAll("-"," ")}</option>)}</select></label><div><small>Submission deadline · IST</small><strong>{formatDate(tender?.closesAt,true)}</strong></div><div><small>Preparation progress</small><strong>{bid.tasks.filter(t=>t.done).length} of {bid.tasks.length} tasks complete</strong></div></div>
 <div className="detail-columns mt"><section className="panel form-panel"><SectionHeader title="Preparation checklist"><button type="button" className="button secondary small" disabled={bid.tasks.length>=200} onClick={()=>setBid(b=>({...b,tasks:[...b.tasks,{id:crypto.randomUUID(),title:"New preparation task",done:false,assignee:"",dueAt:"",notes:"",requirementId:"",changed:false}]}))}><Plus size={18}/>Add task</button></SectionHeader>
 <div className="row wrap"><AsyncButton className="text-button" pending="Syncing requirements…" disabled={dirty} onClick={()=>act({action:"bid.sync",id:bid.id},"Confirmed requirements synced")}><RefreshCw size={18}/>Sync new requirements</AsyncButton><button type="button" className="text-button" onClick={()=>download("biddesk-checklist.csv",csv(bid.tasks as unknown as Record<string,unknown>[],["title","done","assignee","dueAt","notes","requirementId","changed"]))}><Download size={18}/>Export checklist</button></div>
 {dirty&&<p className="muted small-text">Save your edits before syncing additional requirements.</p>}{!bid.tasks.length&&<p className="info-box">Add your first task, or confirm tender requirements and sync them here.</p>}
 {bid.tasks.map((t,i)=><TaskEditor key={t.id} t={t} i={i} edit={edit} onRemove={()=>setBid(b=>({...b,tasks:b.tasks.filter(x=>x.id!==t.id)}))}/>)}</section>
 <aside className="stack"><section className="panel form-panel"><SectionHeader title="Decision & notes"/><label>Bid / no-bid rationale<textarea rows={4} value={bid.decision} onChange={e=>setBid({...bid,decision:e.target.value})} placeholder="Why pursue or decline this opportunity?"/></label><label>Workspace notes<textarea rows={4} value={bid.notes} onChange={e=>setBid({...bid,notes:e.target.value})}/></label><p className="muted small-text mt">Pipeline stages record your progress. Submit bids on the official tender portal.</p></section>{bid.events.length>0&&<section className="panel form-panel"><details><summary>Change history ({bid.events.length})</summary><div className="form-flow disclosure-body">{bid.events.map((e,i)=><p key={i}><strong>{formatDate(e.at,true)}</strong><br/>{e.message}</p>)}</div></details></section>}</aside></div></fieldset><ReadinessPanel tenderId={bid.tenderId}/><SaveBar dirty={dirty} busy={busy} onSave={save}/></>;
}

function TaskEditor({t,i,edit,onRemove}:{t:Task;i:number;edit:(id:string,patch:Partial<Task>)=>void;onRemove:()=>void}){const [expanded,setExpanded]=useState(t.title==="New preparation task");return <div className={`task-editor ${t.done?"completed":""}`}><div className="task-summary"><input type="checkbox" aria-label={`Complete task ${i+1}`} checked={t.done} onChange={e=>edit(t.id,{done:e.target.checked,changed:e.target.checked?false:t.changed})}/><span className="task-title">{t.title}</span><button type="button" aria-label={`Delete task ${i+1}`} className="icon-button" onClick={onRemove}><Trash2 size={18}/></button></div>
 {t.changed&&<Badge tone="amber">Requirement changed — review this task</Badge>}<details open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Edit task {i+1}{t.dueAt?` · Due ${formatDate(t.dueAt)}`:" · Set a deadline"}</summary><div className="form-flow disclosure-body"><label>Task title<input aria-label={`Task ${i+1} title`} value={t.title} onChange={e=>edit(t.id,{title:e.target.value})}/></label><div className="form-grid"><label>Responsible person<input value={t.assignee} onChange={e=>edit(t.id,{assignee:e.target.value})} placeholder="Name or role"/></label><label>Internal deadline<input type="date" value={t.dueAt.slice(0,10)} onChange={e=>edit(t.id,{dueAt:e.target.value})}/></label></div><label>Evidence / task notes<textarea rows={3} value={t.notes} onChange={e=>edit(t.id,{notes:e.target.value})} placeholder="Document references, questions, or next steps"/></label></div></details></div>;}
