"use client";
import { SavedSearches, ReadinessPanel } from "./workflow";
import { AIMatching } from "./ai-matching";
import { useState,useEffect } from "react";
import { useSearchParams,useRouter } from "next/navigation";
import Link from "next/link";
import { Search,SlidersHorizontal,ArrowRight,Bookmark,Download,GitCompareArrows,X,ChevronLeft,ChevronRight } from "lucide-react";
import type { Tender, Requirement } from "@/lib/schemas";
import { csv,formatDate,formatMoney,statusOf,assess } from "@/lib/domain";
import { useWorkspace,useAction,read } from "./context";
import { Badge,Empty,Loading,Modal,AsyncButton,ErrorState,download } from "./ui";

export function TenderRows({tenders,selection,onSelect,onPreview}:{tenders:Tender[];selection?:string[];onSelect?:(id:string)=>void;onPreview?:(t:Tender)=>void}) {
 const {data}=useWorkspace(),act=useAction();
 return <div className="table-wrap"><table className="tender-table"><thead><tr>{onSelect&&<th className="check-col">Compare</th>}<th>Opportunity</th><th>Location</th><th>Est. value</th><th>Deadline · IST</th><th aria-label="Actions"/></tr></thead><tbody>{tenders.map(t=><tr key={t.id}>
 {onSelect&&<td className="select-cell"><input aria-label={`Compare ${t.reference}`} type="checkbox" checked={selection?.includes(t.id)||false} disabled={!selection?.includes(t.id)&&(selection?.length||0)>=4} onChange={()=>onSelect(t.id)}/><span className="mobile-label">Compare</span></td>}
 <td className="opportunity-cell"><div className="row tender-meta"><Badge tone={statusOf(t)==="active"?"green":statusOf(t)==="closed"?"neutral":"blue"}>{statusOf(t)}</Badge></div><Link className="tender-title" href={`/tenders/${t.id}`}>{t.title}</Link><small className="authority">{t.authority || "Authority not published"}</small>{onPreview&&<button className="preview-link" onClick={()=>onPreview(t)}>Quick preview <ArrowRight size={16}/></button>}</td>
 <td><span className="mobile-label">Location</span><span className="location">{[t.city,t.state||t.country].filter(Boolean).join(", ")}</span></td><td className="money"><span className="mobile-label">Est. value</span>{formatMoney(t.value,t.currency)}</td><td className="deadline-cell"><span className="mobile-label">Deadline · IST</span><strong className="date-cell">{formatDate(t.closesAt,true)}</strong>{t.closesAt.length===10&&<small>Confirm exact time in the notice</small>}</td>
 <td className="bookmark-cell"><AsyncButton aria-label={data.favorites.includes(t.id)?`Unsave ${t.reference}`:`Save ${t.reference}`} className={`icon-button bookmark ${data.favorites.includes(t.id)?"saved":""}`} pending="" onClick={()=>act({action:"favorite",id:t.id,saved:!data.favorites.includes(t.id)},data.favorites.includes(t.id)?"Removed from saved tenders":"Tender saved")}><Bookmark size={20} fill={data.favorites.includes(t.id)?"currentColor":"none"}/></AsyncButton></td></tr>)}</tbody></table></div>;
}
type SearchResult={tenders:Tender[];total:number;pages:number;page:number;freshness?:{state:string;fetchedAt:string;warning?:string}};
const states=["Andaman & Nicobar Islands","Chandigarh","Dadra & Nagar Haveli and Daman & Diu","Lakshadweep","Puducherry","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu & Kashmir","Jharkhand","Karnataka","Kerala","Ladakh","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"];
const filterLabels:Record<string,string>={q:"Search",state:"State",category:"Category",authority:"Authority",source:"Source portal",buyer:"Buyer group",classification:"Type",min:"Min. value",max:"Max. value",from:"Closing from",to:"Closing to"};
export function Discovery(){
 const {data}=useWorkspace(),p=useSearchParams(),router=useRouter();
 const [response,setResponse]=useState<{key:string;result?:SearchResult;error?:string}|null>(null),[revision,setRevision]=useState(0),[selection,setSelection]=useState<string[]>([]),[preview,setPreview]=useState<Tender|null>(null),[filters,setFilters]=useState(false);
 const query=p.toString(),saved=p.get("favorites")==="true",matching=p.get("recommended")==="true",favoritesKey=saved?data.favorites.join(","):"",requestKey=`${query}:${favoritesKey}:${revision}`;
 const pending=!matching&&response?.key!==requestKey,result=response?.result,error=pending?"":response?.error,ready=!pending&&!error;
 useEffect(()=>{if(matching)return;const ac=new AbortController();read<SearchResult>(`mode=tenders&${query}`,ac.signal).then(result=>{if(!ac.signal.aborted)setResponse({key:requestKey,result});}).catch(e=>{if(!ac.signal.aborted)setResponse({key:requestKey,error:e.message});});return()=>ac.abort();},[query,matching,requestKey]);
 const [sourceOptions,setSourceOptions]=useState<{categories:{name:string}[];sources:{name:string;display_name:string}[];buyers:{id:string;label:string}[]}>({categories:[],sources:[],buyers:[]}),[optionsLoading,setOptionsLoading]=useState(true),[optionsError,setOptionsError]=useState(""),[optionsRevision,setOptionsRevision]=useState(0);
 useEffect(()=>{const ac=new AbortController();read<typeof sourceOptions>("mode=source-options",ac.signal).then(v=>{setSourceOptions(v);setOptionsError("");}).catch(e=>{if(!ac.signal.aborted)setOptionsError(e.message);}).finally(()=>{if(!ac.signal.aborted)setOptionsLoading(false);});return()=>ac.abort();},[optionsRevision]);
 function set(key:string,value:string){const n=new URLSearchParams(query);if(value)n.set(key,value);else n.delete(key);if(key!=="page")n.delete("page");router.push("/discover?"+n.toString());}
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get("q")||"");if(value===(p.get("q")||""))setRevision(v=>v+1);else set("q",value);}
 const active=[...p].filter(([key])=>filterLabels[key]);
 const clearHref=saved?"/discover?favorites=true":"/discover";
 if(matching)return <><div className="page-heading"><div><h1>Profile matches</h1><p>Explore opportunities related to your company’s capabilities.</p></div><div className="page-actions"><Link href="/discover" className="button secondary">Keyword discovery</Link></div></div><AIMatching/></>;
 return <><div className="page-heading"><div><h1>Discover tenders</h1><p>Find an opportunity, review the requirements, and prepare your bid.</p></div><div className="page-actions"><Link href="/discover?recommended=true&start=true" className="button secondary">Find tenders matching my profile</Link></div></div>
 <nav className="mode-switch" aria-label="Tender collection"><Link href="/discover" aria-current={!saved?"page":undefined}>All tenders</Link><Link href="/discover?favorites=true" aria-current={saved?"page":undefined}>Saved</Link></nav>
 <div className="panel search-panel"><form className="search-box" onSubmit={search}><Search size={20}/><input key={p.get("q")} name="q" defaultValue={p.get("q")||""} placeholder="Keyword, authority or reference" aria-label="Search tenders"/><button className="button" disabled={pending}><Search size={18}/>Search</button></form>
 <div className="filter-row"><label>State<select value={p.get("state")||""} onChange={e=>set("state",e.target.value)}><option value="">All states</option>{states.map(v=><option key={v}>{v}</option>)}</select></label><label>Category<select disabled={!saved&&optionsLoading} value={p.get("category")||""} onChange={e=>set("category",e.target.value)}><option value="">{!saved&&optionsLoading?"Loading categories…":"All categories"}</option>{(saved?[...new Set(data.tenders.filter(t=>data.favorites.includes(t.id)).map(t=>t.category))].sort():sourceOptions.categories.map(c=>c.name)).map(v=><option key={v}>{v}</option>)}</select></label><button className="button secondary" aria-expanded={filters} aria-controls="advanced-filters" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={18}/>{filters?"Fewer filters":"More filters"}</button></div>
 {optionsError&&!saved&&<ErrorState message="Some filter options could not be loaded. Keyword search is still available." onRetry={()=>{setOptionsLoading(true);setOptionsRevision(v=>v+1);}}/>}
 {filters&&<form id="advanced-filters" key={query} onSubmit={e=>{e.preventDefault();const n=new URLSearchParams(query);for(const [k,v] of new FormData(e.currentTarget)){if(v)n.set(k,String(v));else n.delete(k);}n.delete("page");router.push("/discover?"+n.toString());}}><div className="advanced-filters"><label>Authority<input name="authority" defaultValue={p.get("authority")||""} placeholder="Organisation name"/></label>{!saved&&<><label>Source portal<select name="source" disabled={optionsLoading} defaultValue={p.get("source")||""}><option value="">All sources</option>{sourceOptions.sources.map(v=><option value={v.name} key={v.name}>{v.display_name}</option>)}</select></label><label>Buyer group<select name="buyer" disabled={optionsLoading} defaultValue={p.get("buyer")||""}><option value="">All buyers</option>{sourceOptions.buyers.map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></label><label>Procurement type<select name="classification" defaultValue={p.get("classification")||""}><option value="">All types</option>{["Works","Goods","Services","Consultancy"].map(v=><option key={v}>{v}</option>)}</select></label></>}{["min","max"].map(k=><label key={k}>{k==="min"?"Minimum":"Maximum"} value (INR)<input name={k} type="number" min="0" defaultValue={p.get(k)||""}/></label>)}{["from","to"].map(k=><label key={k}>Closing date {k}<input name={k} type="date" defaultValue={p.get(k)||""}/></label>)}</div><div className="page-actions mt"><button className="button secondary" disabled={pending}>Apply filters</button></div></form>}
 {active.length>0&&<div className="active-filters" aria-label="Applied filters">{active.map(([key,value])=><button key={key} className="filter-chip" aria-label={`Remove ${filterLabels[key]} filter`} onClick={()=>set(key,"")}>{filterLabels[key]}: {value}<X size={16}/></button>)}<Link href={clearHref} className="text-button">Clear filters</Link></div>}<SavedSearches query={query}/></div>
 <div className="results-toolbar"><div>{pending?<Loading compact>Updating results…</Loading>:error?<strong>Search unavailable</strong>:<><strong>{result?.total||0} {saved?"saved tenders":"tenders"}</strong>{result?.freshness?.state!=="stale"&&result?.freshness&&<p className="freshness">Results updated · {formatDate(result.freshness.fetchedAt,true)}</p>}</>}</div><div className="row"><select aria-label="Sort tenders" value={p.get("sort")||"deadline"} onChange={e=>set("sort",e.target.value)}><option value="deadline">Closing date</option><option value="newest">Newest published</option><option value="value">Highest value</option></select><button className="text-button" disabled={!ready||!result?.tenders.length} onClick={()=>download("biddesk-displayed-results.csv",csv((result?.tenders||[]) as unknown as Record<string,unknown>[],["title","reference","authority","value","closesAt","sourceUrl","checkedAt"]))}><Download size={18}/>Export this page</button></div></div>
 {ready&&result?.freshness?.state==="stale"&&<p className="info-box" role="status">{result.freshness.warning}</p>}
 <div className="panel search-results" aria-busy={pending}>{pending?<Loading>Searching tenders…</Loading>:error?<div className="form-panel"><ErrorState message={error} onRetry={()=>setRevision(v=>v+1)}/></div>:!result?.tenders.length?<Empty title={saved&&!active.length?"No saved tenders yet":"No tenders match these filters"}><p>{saved&&!active.length?"Save opportunities while browsing to build your shortlist.":"Try a broader keyword or remove a filter."}</p><Link className="button secondary" href={saved&&!active.length?"/discover":clearHref}>{saved&&!active.length?"Browse tenders":"Clear filters"}</Link></Empty>:<TenderRows tenders={result.tenders} selection={selection} onSelect={id=>setSelection(v=>v.includes(id)?v.filter(x=>x!==id):v.length<4?[...v,id]:v)} onPreview={setPreview}/>}
 {ready&&!!result?.total&&<div className="table-footer"><span>Select up to 4 tenders to compare.</span><div className="row"><button aria-label="Previous page" className="icon-button" disabled={result.page<=1} onClick={()=>set("page",String(result.page-1))}><ChevronLeft size={20}/></button><span>Page {result.page} of {Math.max(1,result.pages)}</span><button aria-label="Next page" className="icon-button" disabled={result.page>=result.pages} onClick={()=>set("page",String(result.page+1))}><ChevronRight size={20}/></button></div></div>}</div>
 {selection.length>0&&<div className="compare-bar"><GitCompareArrows size={20}/><strong>{selection.length} selected</strong><Link className="button" href={`/compare?ids=${selection.join(",")}`}>Compare tenders <ArrowRight size={18}/></Link><button aria-label="Clear comparison" className="icon-button" onClick={()=>setSelection([])}><X size={20}/></button></div>}
 {preview&&<Modal wide title="Quick preview" onClose={()=>setPreview(null)}><Badge>{statusOf(preview)}</Badge><h2>{preview.title}</h2><p>{preview.description||"Open the tender for the available scope and documents."}</p><div className="facts"><div><small>Deadline</small><strong>{formatDate(preview.closesAt,true)}</strong></div><div><small>Estimated value</small><strong>{formatMoney(preview.value,preview.currency)}</strong></div></div><Link className="button" href={`/tenders/${preview.id}`}>Open full tender <ArrowRight size={18}/></Link></Modal>}</>;
}
export function Comparison(){
  const {data}=useWorkspace(),p=useSearchParams(),ids=(p.get("ids")||"").split(",").filter(Boolean).slice(0,4).join(",");
  const [response,setResponse]=useState<{key:string;details?:{tender:Tender;requirements:Requirement[]}[];error?:string}|null>(null),[revision,setRevision]=useState(0);const key=`${ids}:${revision}`,details=response?.key===key?response.details:undefined,error=response?.key===key?response.error:undefined;
  useEffect(()=>{const ac=new AbortController();Promise.all(ids.split(",").filter(Boolean).map(id=>read<{tender:Tender;requirements:Requirement[]}>(`mode=tender&cached=true&id=${encodeURIComponent(id)}`,ac.signal))).then(details=>{if(!ac.signal.aborted)setResponse({key,details});}).catch(e=>{if(!ac.signal.aborted)setResponse({key,error:e.message});});return()=>ac.abort();},[ids,key]);
  return <><div className="page-heading"><div><h1>Compare opportunities</h1><p>Review the commitments before choosing your next bid.</p></div><Link href="/discover" className="button secondary">Back to discovery</Link></div>{error?<div className="panel form-panel"><ErrorState message={error} onRetry={()=>setRevision(v=>v+1)}/></div>:!details?<Loading>Loading comparison…</Loading>:!details.length?<div className="panel"><Empty title="Choose tenders to compare"><Link href="/discover">Select up to four in Discover tenders.</Link></Empty></div>:<div className="panel table-wrap"><table className="comparison-table"><thead><tr><th>Requirement</th>{details.map(({tender:t})=><th key={t.id}><Link href={`/tenders/${t.id}`}>{t.title}<ArrowRight size={16}/></Link></th>)}</tr></thead><tbody>{["authority","state","category","value","emd","fee","closesAt","source","checkedAt"].map(key=><tr key={key}><th>{({closesAt:"Deadline",checkedAt:"Source checked",emd:"EMD",fee:"Document fee"} as Record<string,string>)[key]||key}</th>{details.map(({tender:t})=><td key={t.id}>{["value","emd","fee"].includes(key)?formatMoney(t[key as "value"],t.currency):["closesAt","checkedAt"].includes(key)?formatDate(t[key as "closesAt"],true):String(t[key as keyof Tender]||"Not published")}</td>)}</tr>)}<tr><th>Readiness & review coverage</th>{details.map(({tender:t})=><td key={t.id}><ReadinessPanel tenderId={t.id} compact/></td>)}</tr><tr><th>Eligibility review</th>{details.map(({tender:t,requirements})=><td key={t.id}>{!requirements.length?"No requirements reviewed":requirements.map(r=><p key={r.id}><strong>{r.label}</strong><br/>{assess(r,data.company,t.closesAt).outcome}<br/><small>{r.clause||"No source reference"}{r.page?` · Page ${r.page}`:""}</small></p>)}</td>)}</tr></tbody></table></div>}</>;
}
