'use client';
import {useEffect,useRef,useState} from 'react';
import type {SourceDocument,Draft,Citation} from '@/lib/ai/contracts';
import {parsePageSelection,pageBatches} from '@/lib/document-pages';
import {useWorkflow,workflowRequest} from './workflow';
import {aiRequest} from './ai-common';
import {AsyncButton,ErrorState,Loading,Modal} from './ui';
import {useWorkspace} from './context';
type DocumentState={document:SourceDocument;coverage:{page:number;analyzed?:boolean;reviewed?:boolean}[]};
export function DocumentReview({documentId,onDraft,onChange}:{documentId:string;onDraft:(d:Draft)=>void;onChange:()=>void}){
 const {value,error,reload}=useWorkflow<DocumentState>('mode=documents&id='+documentId),{notify}=useWorkspace(),[selection,setSelection]=useState('1'),[progress,setProgress]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState(false),stop=useRef(false);
 if(error)return <ErrorState message={error} onRetry={reload}/>;if(!value)return <Loading compact>Loading page coverage…</Loading>;
 const d=value.document;
 async function remaining(){if(!value)return;stop.current=false;setBusy(true);try{const pages=value.document.pages.filter(p=>p.text.trim().length>=30&&!value.coverage.some(c=>c.page===p.page&&c.analyzed));const batches=pageBatches(pages.map(p=>({page:p.page,characters:p.text.length})));for(let i=0;i<batches.length&&!stop.current;i++){let count=1;for(let chunkIndex=0;chunkIndex<count&&!stop.current;chunkIndex++){setProgress(`Analyzing batch ${i+1} of ${batches.length} · section ${chunkIndex+1}`);const r=await aiRequest<{draft:Draft;totalChunks:number}>({action:'extract',documentId,pages:batches[i],chunkIndex});count=r.totalChunks;onDraft(r.draft);}}setProgress(stop.current?'Paused. Completed sections are saved.':'Remaining readable pages analyzed. Review every batch in Previous analyses.');reload();onChange();}catch(e){setProgress('Analysis paused. Completed sections are retained.');notify(String(e),true);reload();}finally{setBusy(false);}}
 return <div className="document-coverage form-flow mt"><h3>Supplied-page coverage</h3><p>{value.coverage.filter(c=>c.analyzed).length} analyzed · {value.coverage.filter(c=>c.reviewed).length} human-reviewed · {d.totalPages} supplied pages</p><div className="page-status-grid">{d.pages.map(p=><button type="button" key={p.page} className="button secondary small" onClick={()=>{setSelection(String(p.page));setView(true);}} aria-label={`Page ${p.page}: ${value.coverage.find(c=>c.page===p.page)?.reviewed?'reviewed':value.coverage.find(c=>c.page===p.page)?.analyzed?'analyzed':p.text.trim().length<30?'needs OCR or visual review':'unreviewed'}`}>{p.page} · {value.coverage.find(c=>c.page===p.page)?.reviewed?'Reviewed':value.coverage.find(c=>c.page===p.page)?.analyzed?'Analyzed':p.text.trim().length<30?'Scan':'Unreviewed'}</button>)}</div><label>Pages to review or OCR<input value={selection} onChange={e=>setSelection(e.target.value)} placeholder="1-5,8"/></label><div className="row wrap"><button className="button secondary" type="button" disabled={busy} onClick={()=>void remaining()}>Analyze remaining pages</button>{busy&&<button type="button" className="button secondary" onClick={()=>{stop.current=true;}}>Stop after current section</button>}<AsyncButton pending="Saving review…" disabled={busy} onClick={async()=>{try{await workflowRequest({action:'document.review',documentId,pages:parsePageSelection(selection,d.totalPages),reviewed:true});onChange();}catch(e){notify(String(e),true);}}}>Mark selected pages human-reviewed</AsyncButton><AsyncButton pending="Updating…" disabled={busy} onClick={async()=>{try{await workflowRequest({action:'document.review',documentId,pages:parsePageSelection(selection,d.totalPages),reviewed:false});onChange();}catch(e){notify(String(e),true);}}}>Mark unreviewed</AsyncButton><AsyncButton pending="Reading scanned pages…" disabled={busy||!d.fileId} onClick={async()=>{try{const pages=parsePageSelection(selection,d.totalPages);for(const page of pages){setProgress(`Reading scan page ${page}`);await workflowRequest({action:'ocr',documentId,pages:[page]});}setProgress('OCR text saved. Check it against the original page before analyzing.');onChange();}catch(e){notify(String(e),true);}}}>OCR selected pages</AsyncButton><AsyncButton pending="Deleting…" disabled={busy} onClick={async()=>{if(!window.confirm('Delete this document and its retained PDF? Linked findings will need review.'))return;try{await workflowRequest({action:'document.delete',documentId});onChange();}catch(e){notify(String(e),true);}}}>Delete document</AsyncButton></div>{progress&&<p role="status">{progress}</p>}{view&&<DocumentReader documentId={documentId} page={Number(selection)||1} onClose={()=>setView(false)}/>}</div>;
}
export function CitationReader({citation}:{citation:Citation}){const [open,setOpen]=useState(false);return <><button className="text-button" type="button" onClick={()=>setOpen(true)}>Open cited page</button>{open&&<DocumentReader documentId={citation.documentId} page={citation.page} quote={citation.quote} onClose={()=>setOpen(false)}/>}</>;}
function DocumentReader({documentId,page,quote,onClose}:{documentId:string;page:number;quote?:string;onClose:()=>void}){const {value,error,reload}=useWorkflow<DocumentState>('mode=documents&id='+documentId),canvas=useRef<HTMLCanvasElement>(null),[pageNo,setPageNo]=useState(page),[renderError,setRenderError]=useState('');const fileId=value?.document.fileId;useEffect(()=>{if(!fileId)return;let cancelled=false;let destroy:(()=>Promise<void>)|undefined;(async()=>{try{const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const task=pdfjs.getDocument({url:'/api/files?id='+fileId});destroy=()=>task.destroy();const pdf=await task.promise;if(cancelled)return;const p=await pdf.getPage(pageNo),initial=p.getViewport({scale:1.3}),viewport=initial.width*initial.height>12000000?p.getViewport({scale:1.3*Math.sqrt(12000000/(initial.width*initial.height))}):initial,target=canvas.current;if(!target||cancelled)return;target.width=viewport.width;target.height=viewport.height;await p.render({canvas:target,viewport}).promise;if(!cancelled)setRenderError('');}catch{if(!cancelled)setRenderError('Original PDF could not be rendered. Retained text is shown below.');}})();return()=>{cancelled=true;void destroy?.();};},[fileId,pageNo]);return <Modal wide title={value?.document.name||'Document page'} onClose={onClose}>{error?<ErrorState message={error} onRetry={reload}/>:!value?<Loading/>:<><label>PDF page<input type="number" min="1" max={value.document.totalPages} value={pageNo} onChange={e=>setPageNo(Math.max(1,Math.min(value.document.totalPages,Number(e.target.value)||1)))}/></label>{quote&&<blockquote>{quote}</blockquote>}{renderError&&<p role="alert">{renderError}</p>}{fileId?<canvas className="document-canvas" ref={canvas}/>:<p>Original PDF not retained. Reattach it to view the page image.</p>}<details open={!fileId}><summary>Retained page text{value.document.ocr?' · includes OCR':''}</summary><div className="form-flow disclosure-body"><p className="pre-wrap">{value.document.pages.find(p=>p.page===pageNo)?.text||'No readable text. Inspect the original page.'}</p></div></details></>}</Modal>;}
