import {resolve4} from "node:dns/promises";
import {request} from "node:https";
import {Worker} from "node:worker_threads";
import path from "node:path";
import {AiError} from "./runtime";
import {hash} from "./grounding";
import type {SourceDocument} from "./contracts";
export function allowedDocumentUrl(raw:string){const u=new URL(raw);if(u.protocol!=="https:"||u.hostname!=="www.isro.gov.in"||u.port||u.username||u.password||!u.pathname.startsWith("/media_isro/pdf/Tenders/")||!u.pathname.toLowerCase().endsWith(".pdf")||/%2f|%5c|%2e/i.test(u.pathname)||u.search||u.hash)throw new AiError("This document source is not supported. Open the official source and upload the PDF instead.");return u;}
export function publicIPv4(ip:string){const a=ip.split(".").map(Number);return a.length===4&&a.every(n=>Number.isInteger(n)&&n>=0&&n<=255)&&a[0]>0&&a[0]<224&&![10,127].includes(a[0])&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&(a[1]===168||a[1]===0))&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&(a[1]===18||a[1]===19));}
export async function downloadOfficial(raw:string):Promise<Buffer>{const u=allowedDocumentUrl(raw);const ips=await resolve4(u.hostname);if(!ips.length||!ips.every(publicIPv4))throw new AiError("Source resolved to an unsupported destination.");const address=ips[0];return new Promise((resolve,reject)=>{const req=request(u,{method:"GET",headers:{"User-Agent":"BidDesk/0.2 official-notice-review"},family:4,lookup:(_hostname,_options,cb)=>cb(null,address,4)},res=>{if(res.statusCode!==200){res.resume();reject(new AiError("Official document is unavailable or redirected. Upload a local copy instead."));return;}const type=res.headers["content-type"]||"";if(type&&!/application\/(pdf|octet-stream)/i.test(type)){res.resume();reject(new AiError("The source did not return a PDF."));return;}let bytes=0;const parts:Buffer[]=[];res.on("data",(part:Buffer)=>{bytes+=part.length;if(bytes>20*1024*1024){req.destroy(new AiError("PDF exceeds 20 MB."));return;}parts.push(part);});res.on("error",reject);res.on("end",()=>{const data=Buffer.concat(parts);if(!data.subarray(0,1024).includes(Buffer.from("%PDF-"))){reject(new AiError("The source did not return a valid PDF."));return;}resolve(data);});});const timer=setTimeout(()=>req.destroy(new AiError("Official source timed out. Upload a local copy instead.")),30000);req.on("error",()=>reject(new AiError("Official document could not be retrieved within the size/time limits.")));req.on("close",()=>clearTimeout(timer));req.end();});}
export async function extractPdf(data:Buffer):Promise<Pick<SourceDocument,"pages"|"totalPages"|"warnings">>{if(!data.length||data.length>20*1024*1024)throw new AiError("Choose a nonempty PDF under 20 MB.");return new Promise((resolve,reject)=>{const worker=new Worker(path.join(process.cwd(),"scripts/pdf-extract-worker.mjs"),{workerData:{pdfBase64:data.toString("base64")},resourceLimits:{maxOldGenerationSizeMb:256}});const timer=setTimeout(()=>{void worker.terminate();reject(new AiError("PDF extraction timed out. Upload a smaller excerpt."));},30000);worker.once("message",result=>{clearTimeout(timer);void worker.terminate();if(result.error)reject(new AiError(result.error));else resolve(result);});worker.once("error",error=>{console.error("PDF worker failure",{name:error.name,code:"code" in error?error.code:undefined});clearTimeout(timer);reject(new AiError("PDF text extraction failed."));});worker.once("exit",code=>{clearTimeout(timer);if(code!==0)reject(new AiError("PDF extraction ended before completion."));});});}
export const documentKey=(tenderId:string,version:string,index:number,url:string)=>hash([tenderId,version,index,url]).slice(0,32);
