import {GoogleGenAI,ThinkingLevel} from "@google/genai";
import {z} from "zod";
import {providerSchema} from "./provider-schema";
import {AiError,aiConfig,requireAI,testMode,providerSlot,reserve,logUsage} from "./runtime";
import {instruction,PROMPT_VERSION} from "./contracts";
import {cached} from "./runtime";
import {stubGenerate,stubEmbedding} from "./test-provider";
export function safeProviderError(e:unknown){if(e instanceof AiError)return e;const status=typeof e==="object"&&e&&"status" in e?Number(e.status):0;return new AiError(status===429?"Gemini quota is exhausted. Retry later; existing results are preserved.":status===401||status===403?"Gemini rejected API access. Check the configured key and project.":status===404?"Configured Gemini model is unavailable to this project.":"Gemini did not complete the request. Retry or use manual review.",status===429?429:503);}
const client=()=>new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY,httpOptions:{timeout:40000}});
export async function generate<T>(ownerId:string,task:string,input:unknown,schema:z.ZodType<T>,system=instruction){requireAI();const config=aiConfig();return cached(ownerId,["generation",task,input,config.generationModel,PROMPT_VERSION],()=>providerSlot(ownerId,async()=>{const contents=JSON.stringify(input);try{if(testMode()){await reserve(ownerId,"generation");return schema.parse(stubGenerate(task,input));}const ai=client();const count=await ai.models.countTokens({model:config.generationModel,contents:system+"\n"+contents});if((count.totalTokens||0)>12000)throw new AiError("AI input is too long. Select fewer pages or evidence items.",413);for(let attempt=0;attempt<2;attempt++){await reserve(ownerId,"generation");try{const response=await ai.models.generateContent({model:config.generationModel,contents,config:{systemInstruction:system,responseMimeType:"application/json",responseJsonSchema:providerSchema(schema),maxOutputTokens:4000,temperature:0.1,...(config.generationModel.startsWith("gemini-2.5")?{thinkingConfig:{thinkingBudget:512}}:config.generationModel.startsWith("gemini-3.")?{thinkingConfig:{thinkingLevel:ThinkingLevel.LOW}}:{})}});await logUsage(ownerId,config.generationModel,task,{input:response.usageMetadata?.promptTokenCount||0,output:response.usageMetadata?.candidatesTokenCount||0,thinking:response.usageMetadata?.thoughtsTokenCount||0});if(response.candidates?.[0]?.finishReason!=="STOP"||!response.text)throw new AiError("Gemini returned incomplete or blocked output. Select fewer pages or review manually.",422);const parsed=schema.safeParse(JSON.parse(response.text));if(!parsed.success)throw new AiError("Gemini response failed validation. No draft was applied.",422);return parsed.data;}catch(e){await logUsage(ownerId,config.generationModel,task,{input:0,output:0,thinking:0},"failed-or-unknown");const status=typeof e==="object"&&e&&"status" in e?Number(e.status):0;if(attempt===0&&[429,500,502,503].includes(status)){await new Promise(r=>setTimeout(r,1500));continue;}throw e;}}throw new AiError("Gemini request failed.",503);}catch(e){throw safeProviderError(e);}}));}
export async function embed(ownerId:string,text:string,role:"query"|"document"){requireAI();if(text.length>7000)throw new AiError("Matching text is too long.",413);const c=aiConfig();return cached(ownerId,["embedding",c.embeddingModel,768,role,text,PROMPT_VERSION],()=>providerSlot(ownerId,async()=>{await reserve(ownerId,"embedding");if(testMode())return stubEmbedding(text);try{const response=await client().models.embedContent({model:c.embeddingModel,contents:`${role==="query"?"Find procurement opportunities for this supplier capability profile":"Represent this procurement scope for supplier capability matching"}:\n${text}`,config:{outputDimensionality:768}});const vector=response.embeddings?.[0]?.values;if(response.embeddings?.length!==1||vector?.length!==768||vector.some(n=>!Number.isFinite(n)))throw new AiError("Gemini returned an invalid embedding.",422);await logUsage(ownerId,c.embeddingModel,"embedding",{input:Math.ceil(text.length/4),output:0,thinking:0},"success-input-estimate");return vector;}catch(e){throw safeProviderError(e);}}));}
