import {randomUUID} from "node:crypto";
import {getDb,getClient} from "../db";
import {hash} from "./grounding";
export class AiError extends Error {constructor(message:string,public status=400){super(message);}}
export function aiConfig(){return {enabled:process.env.BIDDESK_AI_ENABLED!=="false",configured:!!process.env.GEMINI_API_KEY,generationModel:process.env.GEMINI_GENERATION_MODEL||"gemini-3.6-flash",embeddingModel:process.env.GEMINI_EMBEDDING_MODEL||"gemini-embedding-2",dataMode:process.env.BIDDESK_AI_DATA_MODE==="private-enabled"?"private-enabled":"public-demo",generationLimit:limit("BIDDESK_AI_GENERATION_CALLS_PER_DAY",30),embeddingLimit:limit("BIDDESK_AI_EMBEDDING_ITEMS_PER_DAY",200)};}
function limit(key:string,fallback:number){const n=Number(process.env[key]);return Number.isInteger(n)&&n>0&&n<=10000?n:fallback;}
export function testMode(){const enabled=process.env.BIDDESK_AI_TEST_STUB==="1";if(enabled&&!/^biddesk_test_[a-f0-9]{16}$/.test(process.env.MONGODB_DB||""))throw new AiError("Test provider is restricted to an isolated test database.",503);return enabled;}
export function requireAI(){const c=aiConfig();if(!c.enabled)throw new AiError("AI is disabled. Manual review remains available.",503);if(!c.configured&&!testMode())throw new AiError("Add GEMINI_API_KEY to .env.local and restart to enable Gemini.",503);}
let ready:Promise<unknown>|undefined;
export async function aiIndexes(){if(!ready)ready=(async()=>{const db=await getDb();await Promise.all([db.collection("aiCache").createIndex({ownerId:1,updatedAt:-1}),db.collection("aiDocuments").createIndex({ownerId:1,tenderId:1,version:1}),db.collection("aiDrafts").createIndex({ownerId:1,tenderId:1,version:1}),db.collection("aiFindings").createIndex({ownerId:1,tenderId:1},{unique:true}),db.collection("aiProfiles").createIndex({ownerId:1,tenderId:1},{unique:true}),db.collection("aiJudgments").createIndex({ownerId:1,tenderId:1,requirementId:1},{unique:true}),db.collection("aiEligibility").createIndex({ownerId:1,tenderId:1,generatedAt:-1}),db.collection("aiLeases").createIndex({expiresAt:1},{expireAfterSeconds:0})]);})().catch(e=>{ready=undefined;throw e;});await ready;}
type Cache<T>={_id:string;ownerId:string;state:"running"|"done";token:string;expiresAt:Date;updatedAt:Date;value?:T};
export async function cached<T>(ownerId:string,key:unknown,work:()=>Promise<T>):Promise<{value:T;cached:boolean}>{await aiIndexes();const db=await getDb(),c=db.collection<Cache<T>>("aiCache"),id=hash([ownerId,key]);const old=await c.findOne({_id:id});if(old?.state==="done")return {value:old.value!,cached:true};const token=randomUUID(),now=new Date();try {const lease=await c.findOneAndUpdate({_id:id,$or:[{expiresAt:{$lte:now}},{state:{$exists:false}}]},{$set:{ownerId,state:"running",token,expiresAt:new Date(Date.now()+180000),updatedAt:now}},{upsert:true,returnDocument:"after"});if(!lease)throw new Error("busy");}catch{throw new AiError("This analysis is already running. Wait briefly, then retry to resume.",409);}try{const value=await work();const result=await c.updateOne({_id:id,token},{$set:{value,state:"done",updatedAt:new Date()}});if(!result.matchedCount)throw new AiError("Analysis lease expired. Retry to resume.",409);return {value,cached:false};}catch(e){await c.deleteOne({_id:id,token,state:"running"});throw e;}}
export async function providerSlot<T>(ownerId:string,work:()=>Promise<T>){await aiIndexes();const db=await getDb(),c=db.collection<{_id:string;token:string;expiresAt:Date}>("aiLeases"),token=randomUUID(),keys=["provider",`user:${ownerId}`];try{for(const _id of keys){try{await c.updateOne({_id,expiresAt:{$lte:new Date()}},{$set:{token,expiresAt:new Date(Date.now()+150000)}},{upsert:true});}catch{throw new AiError("Another AI request is running. Retry shortly.",409);}}return await work();}finally{await c.deleteMany({_id:{$in:keys},token});}}
export async function reserve(ownerId:string,kind:"generation"|"embedding"){const config=aiConfig(),cap=kind==="generation"?config.generationLimit:config.embeddingLimit;const session=getClient().startSession();try{await session.withTransaction(async()=>{const c=(await getDb()).collection<{_id:string;count:number}>("aiBudget"),day=new Date().toISOString().slice(0,10);for(const [scope,max] of [["project",cap],[ownerId,kind==="generation"?Math.min(cap,20):cap]] as const){const id=`${day}:${kind}:${scope}`;await c.updateOne({_id:id},{$setOnInsert:{count:0}},{upsert:true,session});const result=await c.updateOne({_id:id,count:{$lt:max}},{$inc:{count:1}},{session});if(!result.matchedCount)throw new AiError("Today's AI allowance is used. Cached results and manual tools remain available.",429);}});}finally{await session.endSession();}}
export async function logUsage(ownerId:string,model:string,kind:string,usage:{input:number;output:number;thinking:number},state="success"){await(await getDb()).collection("aiUsage").insertOne({ownerId,model,kind,...usage,state,at:new Date().toISOString()});}
