import {compareFindings,reconcileFindings,type SavedFindings} from "./conflicts";
import {randomUUID} from "node:crypto";
import {z} from "zod";
import {getDb,getClient} from "../db";
import {tenderFor,effectiveRequirements} from "../store";
import {companySchema,requirementSchema,type Tender,type Requirement} from "../schemas";
import {statusOf} from "../domain";
import {AiError,aiConfig,aiIndexes,cached} from "./runtime";
import {hash,chunkPages,extractionInput,groundedExtraction,mergeExtractions,mergeEligibility,evidenceFor,normalize,cosine,validCitation} from "./grounding";
import {generate,embed} from "./provider";
import {downloadOfficial,extractPdf,documentKey} from "./documents";
import {sourceDocumentSchema,extractionSchema,eligibilitySchema,explanationSchema,extractionInstruction,PROMPT_VERSION,type SourceDocument,type Draft,type Extraction,type MatchingProfile} from "./contracts";

type StoredAnalysis={id:string;ownerId:string;tenderId:string;inputHash:string;generatedAt:string;items:ReturnType<typeof mergeEligibility>[]};
async function currentTender(id:string,owner:string,version?:string){const t=await tenderFor(id,owner);if(version&&t.currentVersion!==version)throw new AiError("This tender changed. Reload before continuing.",409);return t;}
export async function documentFor(id:string,ownerId:string){const d=await(await getDb()).collection<SourceDocument&{linkKey?:string}>("aiDocuments").findOne({id,ownerId});if(!d)throw new AiError("Document not found.",404);if(d.tenderId)await currentTender(d.tenderId,ownerId,d.version);if(d.linkKey){const latest=await(await getDb()).collection<SourceDocument>("aiDocuments").findOne({ownerId,linkKey:d.linkKey},{sort:{retrievedAt:-1}});if(latest&&latest.hash!==d.hash)throw new AiError("A newer copy of this source exists. Analyze the latest document.",409);}return d;}
export async function retrieveDocument(ownerId:string,tenderId:string,version:string,key:string,recheck=false){await aiIndexes();const t=await currentTender(tenderId,ownerId,version),index=t.documents.findIndex((d,i)=>documentKey(t.id,t.currentVersion,i,d.url)===key);if(index<0)throw new AiError("Document does not belong to this tender.",404);const source=t.documents[index],db=await getDb();if(!recheck){const previous=await db.collection<SourceDocument&{linkKey:string}>("aiDocuments").findOne({ownerId,tenderId,version,linkKey:key},{sort:{retrievedAt:-1}});if(previous)return previous;}
 const result=await cached(ownerId,["retrieve",key,recheck?Math.floor(Date.now()/60000):"initial"],async()=>{if(source.pages.length)return {extracted:{pages:source.pages,totalPages:source.pages.length,warnings:["Text retained from a user-reviewed import; official binary was not fetched."]},digest:hash(source.pages),method:"local-upload" as const};const binary=await downloadOfficial(source.url);return {extracted:await extractPdf(binary),digest:hash(binary.toString("base64")),method:"official-link" as const};});await currentTender(tenderId,ownerId,version);const d:SourceDocument={id:hash([ownerId,key,result.value.digest]).slice(0,32),ownerId,tenderId,version,name:source.name,url:source.url,hash:result.value.digest,retrievedAt:new Date().toISOString(),method:result.value.method,...result.value.extracted};const older=await db.collection<SourceDocument>("aiDocuments").find({ownerId,tenderId,version,linkKey:key,hash:{$ne:d.hash}}).toArray();if(older.length)await db.collection("aiProfiles").updateMany({ownerId,tenderId,documentHashes:{$in:older.map(x=>x.hash)}},{$set:{reviewed:false}});await db.collection<SourceDocument&{linkKey:string}>("aiDocuments").updateOne({id:d.id},{$set:{...d,linkKey:key}},{upsert:true});return d;
}
export async function attachPages(ownerId:string,raw:unknown,tenderId="",version=""){await aiIndexes();if(tenderId)await currentTender(tenderId,ownerId,version);const input=z.object({name:z.string().min(1).max(300),pages:z.array(z.object({page:z.number().int().positive(),text:z.string().max(25000)})).min(1).max(250)}).parse(raw);if(new Set(input.pages.map(p=>p.page)).size!==input.pages.length||input.pages.reduce((n,p)=>n+p.text.length,0)>700000)throw new AiError("Invalid pages or excessive text.");const digest=hash(input.pages);const d=sourceDocumentSchema.parse({id:hash([ownerId,tenderId,version,digest]).slice(0,32),ownerId,tenderId,version,name:input.name,url:"",hash:digest,retrievedAt:new Date().toISOString(),method:"local-upload",pages:input.pages,totalPages:input.pages.length,warnings:input.pages.filter(p=>p.text.trim().length<30).map(p=>`Page ${p.page} has little or no readable text.`)});await(await getDb()).collection<SourceDocument>("aiDocuments").updateOne({id:d.id},{$setOnInsert:d},{upsert:true});return d;}
export async function extractChunk(ownerId:string,documentId:string,pages:number[],index:number){const d=await documentFor(documentId,ownerId),chunks=chunkPages(d,pages);if(index<0||index>=chunks.length)throw new AiError("Unknown analysis chunk.");const model=aiConfig().generationModel,inputHash=hash([d.hash,pages,model,PROMPT_VERSION]),id=hash([ownerId,d.id,inputHash]).slice(0,32);const result=await generate(ownerId,"extract",extractionInput(d,chunks[index]),extractionSchema,extractionInstruction);const data=groundedExtraction(result.value,[d]);const db=await getDb();await documentFor(documentId,ownerId);await db.collection<{_id:string;chunks:Record<string,Extraction>}>("aiChunks").updateOne({_id:id},{$set:{[`chunks.${index}`]:data}},{upsert:true});const saved=await db.collection<{_id:string;chunks:Record<string,Extraction>}>("aiChunks").findOne({_id:id});const completed=Object.keys(saved!.chunks).map(Number).sort((a,b)=>a-b);const merged=mergeExtractions(completed.map(i=>saved!.chunks[i]));if(completed.length<chunks.length)merged.warnings.push(`Partial analysis: ${completed.length} of ${chunks.length} chunks completed. Retry to resume.`);merged.warnings.push(...d.warnings,`Only selected pages ${pages.join(", ")} analyzed. Visual content is not interpreted.`);
 const draft:Draft={id,ownerId,tenderId:d.tenderId,version:d.version,inputHash,documentIds:[d.id],data:merged,generatedAt:new Date().toISOString(),model,coverage:[{documentId:d.id,pages}]};await db.collection<Draft>("aiDrafts").updateOne({id,ownerId},{$set:draft},{upsert:true});return {draft,totalChunks:chunks.length,completed,cached:result.cached};}
export async function state(ownerId:string,id:string){const t=await tenderFor(id,ownerId),db=await getDb(),requirements=await effectiveRequirements(t,ownerId);const [documents,drafts,storedFindings,analysis,review]=await Promise.all([db.collection<SourceDocument>("aiDocuments").find({ownerId,tenderId:id,version:t.currentVersion}).sort({retrievedAt:-1}).limit(20).toArray(),db.collection<Draft>("aiDrafts").find({ownerId,tenderId:id}).sort({generatedAt:-1}).limit(8).toArray(),db.collection<SavedFindings>("aiFindings").findOne({ownerId,tenderId:id}),db.collection<StoredAnalysis>("aiEligibility").findOne({ownerId,tenderId:id},{sort:{generatedAt:-1}}),db.collection("reviews").findOne({ownerId,tenderId:id})]);const findings=reconcileFindings(t,storedFindings);const company=companySchema.parse(await db.collection("companies").findOne({ownerId})||{});const inputHash=eligibilityHash(t,requirements,company,documents,findings);const judgments=await db.collection("aiJudgments").find({ownerId,tenderId:id}).toArray();return {version:t.currentVersion,links:t.documents.map((d,i)=>({key:documentKey(t.id,t.currentVersion,i,d.url),name:d.name,url:d.url})),documents,drafts: drafts.map(d=>({...d,stale:d.version!==t.currentVersion||d.documentIds.some(id=>!documents.some(doc=>doc.id===id))})),findings:findings?{...findings,stale:findings.version!==t.currentVersion}:null,analysis:analysis?{...analysis,judgments:judgments.map(j=>({...j,stale:j.inputHash!==inputHash})),stale:analysis.inputHash!==inputHash}:null,reviewHash:hash([requirements,review?.notes||""])};}
export async function applyDraft(ownerId:string,body:Record<string,unknown>){const db=await getDb(),draft=await db.collection<Draft>("aiDrafts").findOne({id:z.string().parse(body.draftId),ownerId});if(!draft)throw new AiError("Draft not found.",404);const t=await currentTender(draft.tenderId,ownerId,draft.version),docs=await Promise.all(draft.documentIds.map(id=>documentFor(id,ownerId)));const selected=z.array(z.object({index:z.number().int().nonnegative(),label:z.string().min(3).max(500),confirmed:z.boolean()})).max(100).parse(body.requirements);const fieldIndexes=z.array(z.number().int().nonnegative()).max(100).parse(body.fields);if(new Set(selected.map(x=>x.index)).size!==selected.length||new Set(fieldIndexes).size!==fieldIndexes.length)throw new AiError("Duplicate selections.");const fields=fieldIndexes.map(i=>draft.data.fields[i]);if(fields.some(f=>!f))throw new AiError("Invalid draft field.");const {conflicts,comparisonNotes}=compareFindings(t,fields);
 const review=await db.collection("reviews").findOne({ownerId,tenderId:t.id}),existing=await effectiveRequirements(t,ownerId);if(body.reviewHash!==hash([existing,review?.notes||""]))throw new AiError("Your private review changed. Reload before applying the draft.",409);
 const additions=selected.map(s=>{const r=draft.data.requirements[s.index];if(!r||!r.citations.every(c=>validCitation(c,docs)))throw new AiError("Invalid source requirement.");return requirementSchema.parse({...r,id:hash([draft.documentIds,s.index,r.citations]).slice(0,32),label:s.label,confirmed:s.confirmed&&!conflicts.length,type:r.complex?"manual":r.type,threshold:r.complex?null:r.threshold,clause:`${docs[0].name} · source excerpt`,page:r.citations[0].page,origin:"ai-assisted"});});
 const merged=new Map(existing.map(r=>[r.id,r]));for(const r of additions)merged.set(r.id,r);if(merged.size>100)throw new AiError("Maximum 100 reviewed requirements.");const session=getClient().startSession();try{await session.withTransaction(async()=>{const current=await db.collection<Tender>("tenders").findOne({id:t.id,currentVersion:t.currentVersion},{session});if(!current)throw new AiError("Tender changed. Reload before applying.",409);const result=await db.collection("reviews").updateOne({ownerId,tenderId:t.id,...(review?{updatedAt:review.updatedAt}: {updatedAt:{$exists:false}})},{$set:{ownerId,tenderId:t.id,version:t.currentVersion,requirements:[...merged.values()],notes:review?.notes||"",updatedAt:new Date().toISOString()}},{upsert:!review,session});if(review&&!result.matchedCount)throw new AiError("Your review changed. Reload and retry.",409);await db.collection<SavedFindings>("aiFindings").updateOne({ownerId,tenderId:t.id},{$set:{ownerId,tenderId:t.id,version:t.currentVersion,draftId:draft.id,fields,conflicts,comparisonNotes,documentHashes:docs.map(d=>d.hash),updatedAt:new Date().toISOString()}},{upsert:true,session});});}finally{await session.endSession();}return {ok:true,conflicts};}
export function eligibilityHash(t:Tender,requirements:Requirement[],company:ReturnType<typeof companySchema.parse>,documents:SourceDocument[],findings:unknown){return hash([t.currentVersion,requirements,company,documents.map(d=>d.hash).sort(),findings,new Date().toISOString().slice(0,10),aiConfig().generationModel,PROMPT_VERSION]);}
export async function reviewEligibility(ownerId:string,id:string){const t=await tenderFor(id,ownerId),db=await getDb(),requirements=await effectiveRequirements(t,ownerId),company=companySchema.parse(await db.collection("companies").findOne({ownerId})||{}),documents=await db.collection<SourceDocument>("aiDocuments").find({ownerId,tenderId:id,version:t.currentVersion}).limit(20).toArray(),findings=reconcileFindings(t,await db.collection<SavedFindings>("aiFindings").findOne({ownerId,tenderId:id}));if(!requirements.length)throw new AiError("Review at least one sourced requirement first.");const evidence=evidenceFor(company);if(!evidence.length)throw new AiError("Add an AI-shareable capability profile or selected project evidence in Company profile.");const grounded=requirements.filter(r=>r.confirmed&&r.citations?.length&&r.citations.every(c=>validCitation(c,documents)));if(!grounded.length)throw new AiError("Analyze documents and confirm source-backed requirements before AI review.");const inputHash=eligibilityHash(t,requirements,company,documents,findings);const result=await generate(ownerId,"eligibility",{requirements:grounded.map(r=>({id:r.id,label:r.label,complex:r.complex||false,citations:r.citations})),evidence,task:"Compare qualitative evidence only. Supporting evidence does not establish qualification. Explicit exceptions and alternatives require review. Use evidence IDs and exact source citations supplied. Financial facts are checked locally."},eligibilitySchema);const items=requirements.map(r=>mergeEligibility(r,company,t.closesAt,result.value.items.find(x=>x.requirementId===r.id),documents));if(findings?.conflicts?.length)for(const item of items)item.outcome="needs review";const current=await state(ownerId,id);const refreshedCompany=companySchema.parse(await db.collection("companies").findOne({ownerId})||{});if(inputHash!==eligibilityHash(await tenderFor(id,ownerId),await effectiveRequirements(t,ownerId),refreshedCompany,current.documents,current.findings?Object.fromEntries(Object.entries(current.findings).filter(([k])=>k!=="stale")):null))throw new AiError("Inputs changed while Gemini was reviewing. Run the review again.",409);const analysis={id:randomUUID(),ownerId,tenderId:id,version:t.currentVersion,inputHash,items,generatedAt:new Date().toISOString(),model:aiConfig().generationModel};await db.collection("aiEligibility").insertOne(analysis);return {...analysis,cached:result.cached};}
export async function publishPrivateProfile(ownerId:string,id:string){const t=await tenderFor(id,ownerId),db=await getDb(),f=reconcileFindings(t,await db.collection<SavedFindings>("aiFindings").findOne({ownerId,tenderId:id,version:t.currentVersion}));if(!f?.fields?.length)throw new AiError("Review and save scope findings before preparing matching.");if(f.conflicts?.length)throw new AiError("Resolve conflicting source facts before preparing matching.");const draft=await db.collection<Draft>("aiDrafts").findOne({id:f.draftId,ownerId});if(!draft)throw new AiError("Source draft is unavailable.");const fields=f.fields as Extraction["fields"];const text=fields.filter(x=>["title","description","category"].includes(x.key)).map(x=>x.value).join("\n").slice(0,6500);if(text.length<50)throw new AiError("More supported scope text is needed for semantic matching.");const profile:MatchingProfile={id:hash([ownerId,id]),ownerId,tenderId:id,version:t.currentVersion,text,hash:hash(text),citations:fields.flatMap(x=>x.citations),documentHashes:f.documentHashes,reviewed:true,createdAt:new Date().toISOString()};await db.collection<MatchingProfile>("aiProfiles").updateOne({ownerId,tenderId:id},{$set:profile},{upsert:true});return profile;}
export async function candidates(ownerId:string,filters:{state?:string;category?:string;min?:number;max?:number}={}){const db=await getDb(),all=await db.collection<Tender>("tenders").find({$or:[{ownerId:null},{ownerId}]},{projection:{documents:0,requirements:0}}).limit(2000).toArray();const visible=all.filter(t=>["active","upcoming deadline"].includes(statusOf(t))&&(!filters.state||t.state===filters.state)&&(!filters.category||t.category===filters.category)&&(filters.min==null||t.currency==="INR"&&t.value!=null&&t.value>=filters.min)&&(filters.max==null||t.currency==="INR"&&t.value!=null&&t.value<=filters.max));const profiles=await db.collection<MatchingProfile>("aiProfiles").find({$or:[{ownerId:null},{ownerId}],reviewed:true,tenderId:{$in:visible.map(t=>t.id)}}).toArray();const result=visible.flatMap(t=>{const profile=profiles.find(p=>p.tenderId===t.id&&p.version===t.currentVersion&&p.ownerId===ownerId)||profiles.find(p=>p.tenderId===t.id&&p.version===t.currentVersion);const fallback=t.category!=="Unclassified"&&t.description.length>100&&!t.description.startsWith("Official ")?t.description:"";const text=profile?.text||fallback;return text?[{id:t.id,title:t.title,state:t.state,category:t.category,version:t.currentVersion,text,hash:hash(text),sourceUrl:t.sourceUrl,checkedAt:t.checkedAt,quality:profile?"Reviewed source text":"Reviewed catalogue description"}]:[];});return {items:result,total:all.length,filtered:visible.length};}
export async function prepareEmbedding(ownerId:string,id:string){const c=await candidates(ownerId),item=c.items.find(t=>t.id===id);if(!item)throw new AiError("Tender is unavailable or lacks reviewed scope text.",404);return embed(ownerId,item.text,"document");}
export function candidateHash(items:{id:string;version:string;hash:string}[]){return hash(items.map(t=>[t.id,t.version,t.hash]).sort((a,b)=>a[0].localeCompare(b[0])));}
export async function match(ownerId:string,filters:{state?:string;category?:string;min?:number;max?:number},explain:boolean){const db=await getDb(),company=companySchema.parse(await db.collection("companies").findOne({ownerId})||{});if(company.aiProfile.trim().length<30)throw new AiError("Add at least 30 characters to your AI-shareable capability profile.");const c=await candidates(ownerId,filters);const companyVector=await embed(ownerId,company.aiProfile,"query");const ranked=[];for(const t of c.items){const config=aiConfig(),key=hash([ownerId,["embedding",config.embeddingModel,768,"document",t.text,PROMPT_VERSION]]);const cachedVector=await db.collection<{_id:string;state:string;value:number[]}>("aiCache").findOne({_id:key,state:"done"});if(cachedVector)ranked.push({...t,similarity:cosine(companyVector.value,cachedVector.value)});}ranked.sort((a,b)=>b.similarity-a.similarity||a.id.localeCompare(b.id));const top=ranked.slice(0,5);let explanations:z.infer<typeof explanationSchema>["items"]=[];if(explain&&top.length){const result=await generate(ownerId,"explain-matches",{capabilities:company.aiProfile,candidates:top.map(t=>({id:t.id,text:t.text})),task:"Explain scope relevance and one limitation for each supplied candidate. Copy an exact quote from its text. Relevance is not eligibility or win probability."},explanationSchema);explanations=result.value.items.filter(e=>top.some(t=>t.id===e.tenderId&&normalize(t.text).includes(normalize(e.quote))));}const latestCompany=companySchema.parse(await db.collection("companies").findOne({ownerId})||{});if(hash(latestCompany.aiProfile)!==hash(company.aiProfile)||candidateHash((await candidates(ownerId,filters)).items)!==candidateHash(c.items))throw new AiError("Inputs changed while ranking. Refresh recommendations.",409);const result={candidateHash:candidateHash(c.items),promptVersion:PROMPT_VERSION,id:hash([ownerId,company.aiProfile,filters,c.items.map(t=>t.hash),aiConfig(),PROMPT_VERSION]),ownerId,profileHash:hash(company.aiProfile),filters,coverage:{visible:c.total,filtered:c.filtered,described:c.items.length,ranked:ranked.length},items:top.map((t,i)=>({...t,rank:i+1,explanation:explanations.find(e=>e.tenderId===t.id)||null})),generatedAt:new Date().toISOString(),model:aiConfig().embeddingModel};await db.collection("aiMatches").updateOne({ownerId},{$set:result},{upsert:true});return result;}

export async function saveJudgment(ownerId:string,body:Record<string,unknown>){
 const input=z.object({tenderId:z.string(),analysisId:z.string(),requirementId:z.string(),outcome:z.enum(["supporting evidence","evidence gap","needs review"]),note:z.string().min(10).max(2000),evidence:z.string().min(3).max(1000)}).parse(body);
 const current=await state(ownerId,input.tenderId),a=current.analysis;
 if(!a||a.id!==input.analysisId||a.stale)throw new AiError("The analysis changed. Refresh before recording a judgment.",409);
 const item=a.items.find((r:{requirementId:string})=>r.requirementId===input.requirementId);if(!item)throw new AiError("Unknown reviewed requirement.");
 if(item.outcome==="not satisfied"&&input.outcome==="supporting evidence")throw new AiError("A numeric or expiry failure cannot be overridden. Correct the underlying evidence first.");
 const judgment={...input,ownerId,inputHash:a.inputHash,recordedAt:new Date().toISOString()};
 await(await getDb()).collection("aiJudgments").updateOne({ownerId,tenderId:input.tenderId,requirementId:input.requirementId},{$set:judgment},{upsert:true});return judgment;
}
