import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {getDb} from '../db';
import {AiError} from '../ai/runtime';
import {extractPdf} from '../ai/documents';
import {attachPages} from '../ai/service';
import {tenderFor} from '../store';
import {readZip} from './zip';
const digest=(s:string|Buffer)=>createHash('sha256').update(s).digest('hex');
const root=path.join(process.cwd(),'.local','attachments');
type Grant={_id:string;ownerId:string;tenderId:string;version:string;state:string;expiresAt:Date};
export type Archive={_id:string;ownerId:string;tenderId:string;version:string;hash:string;at:string;expiresAt:Date;entries:{name:string;size:number;pdf:boolean;hash:string}[]};
export async function cleanup(){const db=await getDb();const old=await db.collection<Archive>('attachmentArchives').find({expiresAt:{$lt:new Date()}}).limit(20).toArray();for(const a of old){if(/^[a-f0-9-]{36}$/.test(a._id))await rm(path.join(root,a._id),{recursive:true,force:true});await db.collection<Archive>('attachmentArchives').deleteOne({_id:a._id});}await db.collection<Grant>('attachmentGrants').deleteMany({expiresAt:{$lt:new Date()}});}
export async function grant(ownerId:string,tenderId:string){await cleanup();const t=await tenderFor(tenderId);if(!/^th-\d+$/.test(tenderId))throw new AiError('Extension downloads are available for source portal tenders only.');const token=randomBytes(32).toString('hex');await (await getDb()).collection<Grant>('attachmentGrants').insertOne({_id:digest(token),ownerId,tenderId,version:t.currentVersion,state:'ready',expiresAt:new Date(Date.now()+10*60000)});return {token,bidId:tenderId.slice(3),title:t.title};}
export async function receive(token:string,bytes:Buffer){const db=await getDb();const g=await db.collection<Grant>('attachmentGrants').findOneAndUpdate({_id:digest(token),state:'ready',expiresAt:{$gt:new Date()}},{$set:{state:'consumed'}},{returnDocument:'after'});if(!g)throw new AiError('Transfer grant expired or already used. Generate a new pairing code.',403);const t=await tenderFor(g.tenderId);if(t.currentVersion!==g.version)throw new AiError('Tender changed. Generate a new pairing code.',409);const entries=readZip(bytes),h=digest(bytes);const existing=await db.collection<Archive>('attachmentArchives').findOne({ownerId:g.ownerId,tenderId:t.id,version:g.version,hash:h,expiresAt:{$gt:new Date()}});if(existing)return existing;const id=randomUUID(),dir=path.join(root,id);try{await mkdir(dir,{recursive:true,mode:0o700});for(let i=0;i<entries.length;i++)await writeFile(path.join(dir,String(i)),entries[i].data,{mode:0o600});const record:Archive={_id:id,ownerId:g.ownerId,tenderId:t.id,version:g.version,hash:h,at:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000),entries:entries.map(e=>({name:e.name,size:e.data.length,pdf:e.pdf,hash:digest(e.data)}))};await db.collection<Archive>('attachmentArchives').insertOne(record);return record;}catch(e){await rm(dir,{recursive:true,force:true});throw e;}}
export async function archiveFor(ownerId:string,id:string){const a=await (await getDb()).collection<Archive>('attachmentArchives').findOne({_id:id,ownerId,expiresAt:{$gt:new Date()}});if(!a)throw new AiError('Archive expired or unavailable.',404);return a;}
export async function fileFor(ownerId:string,id:string,index:number){const a=await archiveFor(ownerId,id);if(!a.entries[index])throw new AiError('File not found.',404);return {a,entry:a.entries[index],data:await readFile(path.join(root,a._id,String(index)))};}
export async function analyzeFile(ownerId:string,id:string,index:number){const {a,entry,data}=await fileFor(ownerId,id,index);if(!entry.pdf)throw new AiError('Only PDFs can be analyzed. Other formats are download-only.');const t=await tenderFor(a.tenderId);if(t.currentVersion!==a.version)throw new AiError('Tender changed. Download attachments again.',409);const parsed=await extractPdf(data);const d=await attachPages(ownerId,{name:entry.name,pages:parsed.pages},t.id,t.currentVersion);await (await getDb()).collection('aiDocuments').updateOne({id:d.id,ownerId},{$set:{method:"extension-transfer",attachmentProvenance:{archiveHash:a.hash,fileHash:entry.hash,provider:'tenderhut',bidId:t.id.slice(3),retrievedAt:a.at,url:`https://tenderhut.in/bids/${t.id.slice(3)}/documents/zip`}}});return d;}
