import {z} from 'zod';
import {getDb} from '../db';
import {hash} from '../ai/grounding';
import {normalize,htmlObservation,detailPath,type Observation,type Freshness} from './normalize';
export const searchSchema=z.object({q:z.string().max(200).default(''),source:z.string().max(100).default(''),buyer:z.string().max(500).default(''),classification:z.enum(['','Works','Goods','Services','Consultancy']).default(''),state:z.string().max(100).default(''),location:z.string().max(1000).default(''),category:z.string().max(500).default(''),authority:z.string().max(300).default(''),min:z.coerce.number().nonnegative().optional(),max:z.coerce.number().nonnegative().optional(),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),sort:z.enum(['deadline','newest','value']).default('deadline'),page:z.coerce.number().int().min(1).max(10000).default(1),size:z.coerce.number().int().min(1).max(50).default(15)}).refine(v=>v.min==null||v.max==null||v.min<=v.max,'Minimum exceeds maximum');
export type Search=z.infer<typeof searchSchema>;
export function queryFor(s:Search){const p=new URLSearchParams({sort_by:s.sort==='newest'?'start_date':s.sort==='value'?'value_inr':'end_date',sort_dir:s.sort==='deadline'?'asc':'desc',limit:String(s.size),offset:String((s.page-1)*s.size)});for(const [k,v] of Object.entries({keyword:s.q,source:s.source,buyer:s.buyer,classification:s.classification,state:s.state,location:s.location,category:s.category,organisation:s.authority,min_value:s.min,max_value:s.max,end_after:s.from,end_before:s.to}))if(v!==undefined&&v!=='')p.set(k,String(v));return p.toString();}
let ready:Promise<unknown>|undefined;export async function sourceIndexes(){if(!ready)ready=(async()=>{const db=await getDb();await Promise.all(['sourceCache','sourceObservations','sourceMatches'].map(n=>db.collection(n).createIndex({expiresAt:1},{expireAfterSeconds:0})));})();return ready;}
const flights=new Map<string,Promise<string>>();let active=0,backoff=0;
export async function sourceFetch(path:string){
 if(process.env.BIDDESK_SOURCE_TEST_FIXTURES==='1'){
   if(!/^biddesk_test_[a-f0-9]{16}$/.test(process.env.MONGODB_DB||''))throw new Error('Source fixtures require an isolated test database.');
   const {fixtureResponse}=await import('./test-source');return fixtureResponse(path);
 }
if(!/^\/(bids\?|tender\/|categories$|buyers$|sources$)/.test(path))throw new Error('Unsupported source route.');const pending=flights.get(path);if(pending)return pending;
 const work=(async()=>{if(Date.now()<backoff)throw new Error('source portal temporarily unavailable; retry on your next visit.');if(active>=2)throw new Error('Source is busy. Retained results remain available.');active++;try{const res=await fetch('https://tenderhut.in'+path,{cache:'no-store',redirect:'error',signal:AbortSignal.timeout(12000),headers:{Accept:'application/json, text/html'}});if(!res.ok){if(res.status===429||res.status>=500){const retry=Number(res.headers.get('retry-after'));backoff=Date.now()+Math.min(300000,Math.max(15000,Number.isFinite(retry)?retry*1000:15000));}throw new Error(`source portal returned ${res.status}.`);}const reader=res.body?.getReader();if(!reader)throw new Error('Source returned no body.');const parts:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4*1024*1024){await reader.cancel();throw new Error('Source response exceeds limit.');}parts.push(value);}return Buffer.concat(parts).toString('utf8');}finally{active--;}})();flights.set(path,work);try{return await work;}finally{flights.delete(path);}}
export async function searchSource(search:Search):Promise<{observations:Observation[];total:number;freshness:Freshness}>{await sourceIndexes();const db=await getDb(),key=hash(queryFor(search)),c=db.collection<{_id:string;observations:Observation[];total:number;at:string;expiresAt:Date}>('sourceCache');try{const data=z.object({total:z.number().int().nonnegative(),bids:z.array(z.unknown()).max(50)}).parse(JSON.parse(await sourceFetch('/bids?'+queryFor(search))));const at=new Date().toISOString(),observations=data.bids.map(b=>normalize(b,at));const expiresAt=new Date(Date.now()+7*86400000);await c.updateOne({_id:key},{$set:{observations,total:data.total,at,expiresAt}},{upsert:true});if(observations.length)await db.collection<Observation&{_id:string;expiresAt:Date}>('sourceObservations').bulkWrite(observations.map(o=>({updateOne:{filter:{_id:o.id},update:{$set:{...o,expiresAt}},upsert:true}})));return {observations,total:data.total,freshness:{state:'fresh',fetchedAt:at}};}catch(e){const old=await c.findOne({_id:key});if(!old)throw e;return {observations:old.observations,total:old.total,freshness:{state:'stale',fetchedAt:old.at,warning:'Source unavailable. Showing the last successful response.'}};}}
export async function refreshHTML(o:Observation){return htmlObservation(await sourceFetch(detailPath(o)),o);}
type Options={categories:{name:string}[];sources:{name:string;display_name:string}[];buyers:{id:string;label:string}[]};
let optionsCache:{at:number;value:Options}|undefined;
export async function sourceOptions():Promise<Options>{if(optionsCache&&Date.now()-optionsCache.at<86400000)return optionsCache.value;const result:Options={categories:[],sources:[],buyers:[]};
try{result.categories=z.array(z.object({name:z.string()})).parse(JSON.parse(await sourceFetch('/categories')));}catch{}
try{result.sources=z.array(z.object({name:z.string(),display_name:z.string()})).parse(JSON.parse(await sourceFetch('/sources')));}catch{}
try{const data=JSON.parse(await sourceFetch('/buyers'));const walk=(v:unknown)=>{if(Array.isArray(v)){for(const item of v)walk(item);}else if(v&&typeof v==='object'){const obj=v as Record<string,unknown>;if(typeof obj.id==='string'&&typeof(obj.label||obj.name)==='string')result.buyers.push({id:obj.id,label:String(obj.label||obj.name)});for(const key of ['sections','groups','buckets','subBuckets'])if(obj[key])walk(obj[key]);}};walk(data);}catch{}
optionsCache={at:Date.now(),value:result};return result;}
