import {getDb,ensureIndexes} from '../db';
import {saveTender} from '../store';
import {tenderSchema,type Tender} from '../schemas';
import {mergeFields,externalId,type Observation,type Freshness} from './normalize';
import {refreshHTML} from './client';
let indexes:Promise<unknown>|undefined;
const locks=new Map<string,Promise<unknown>>();
export async function materialize(id:string,refresh=false):Promise<{tender:Tender;freshness:Freshness;metadata:Record<string,string>}>{externalId.parse(id);const previous=locks.get(id)||Promise.resolve();const work=previous.catch(()=>{}).then(()=>materializeUnlocked(id,refresh));locks.set(id,work);try{return await work;}finally{if(locks.get(id)===work)locks.delete(id);}}
async function materializeUnlocked(id:string,refresh:boolean){if(!indexes)indexes=ensureIndexes().catch(e=>{indexes=undefined;throw e;});await indexes;const db=await getDb();const old=await db.collection<Tender>('tenders').findOne({id});const saved=await db.collection<Observation&{_id:string;provenance?:Record<string,string>}>('sourceDurable').findOne({_id:id});const listed=await db.collection<Observation&{_id:string}>('sourceObservations').findOne({_id:id});let o:Observation|undefined= listed&&(!saved||listed.at>saved.at)?listed:saved||undefined;if(!o)throw new Error('Tender is no longer cached. Search for it again.');let warning='';let fields=mergeFields(old?tenderSchema.parse(old):{},o.fields);let raw={...saved?.raw,...o.raw};const provenance={...saved?.provenance};if(o===listed)for(const [key,value] of Object.entries(o.fields))if(value!==null&&value!=='')provenance[key]=`${o.surface} · ${o.at}`;
 if(refresh){try{const html=await refreshHTML(o);fields=mergeFields(fields,html.fields);raw={...raw,...html.raw};for(const key of Object.keys(html.fields))provenance[key]=`html · ${html.at}`;o={...o,at:html.at,surface:'html',fields,raw};}catch{warning='Could not refresh the source page. Retained fields keep their previous observation dates.';}}
 const sourceNote='source portal metadata. Original sources remain authoritative. Exact time may be unavailable; verify the official notice.';fields.sourceNote=sourceNote;fields.source='Public notice';
 await saveTender(fields,id,o.at);await db.collection<Observation&{_id:string;provenance:Record<string,string>}>('sourceDurable').updateOne({_id:id},{$set:{...o,fields,raw,provenance}},{upsert:true});const tender=await db.collection<Tender>('tenders').findOne({id});if(!tender)throw new Error('Tender could not be retained.');return {tender,metadata:{...raw,...Object.fromEntries(Object.entries(provenance).map(([k,v])=>[`Observed ${k}`,v]))},freshness:{state:warning?'stale':'fresh',fetchedAt:o.at,...(warning?{warning}:{})} as Freshness};}
