import {SavedInformationError} from '@/lib/ai/bid-information';
import {z} from "zod";
import {getAuth} from "@/lib/auth";
import {AiError,aiIndexes} from "@/lib/ai/runtime";
import * as service from "@/lib/ai/service";
export const runtime="nodejs";
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"private, no-store"}});
async function owner(req:Request){const s=await getAuth().api.getSession({headers:req.headers});if(!s)throw new AiError("Please sign in again.",401);return s.user.id;}
function failure(e:unknown){if(e instanceof SavedInformationError)return json({error:e.message,savedRevision:e.savedRevision},e.status);if(e instanceof AiError)return json({error:e.message},e.status);if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:"Invalid AI request or response. Review your selected inputs."},400);const msg=e instanceof Error?e.message:"";if(msg==="NOT_FOUND")return json({error:"Record not found"},404);console.error("BidDesk AI request failed:",e instanceof Error?e.name:"Error");return json({error:"The operation failed. Check source availability and database connectivity, or use manual review."},503);}
export async function GET(req:Request){try{const id=await owner(req),p=new URL(req.url).searchParams;await aiIndexes();const tenderId=z.string().regex(/^th-\d+$/).parse(p.get("tenderId"));const state=await service.state(id,tenderId);return json({...state,bidInformation:state.bidInformation.map(({fileText,assessment,...info})=>({...info,hasReadablePdf:!!fileText,checkedAt:assessment?.generatedAt})),documents:state.documents.map(d=>({...d,pages:d.pages.map(page=>({...page,characters:page.text.length,readable:page.text.trim().length>=30,text:""}))}))});}catch(e){return failure(e);}}
export async function POST(req:Request){try{const origin=req.headers.get("origin");if(origin&&origin!==new URL(req.url).origin&&origin!==process.env.BETTER_AUTH_URL)throw new AiError("Invalid request origin.",403);if(Number(req.headers.get("content-length"))>2000000)throw new AiError("AI input exceeds 2 MB.",413);const id=await owner(req),text=await req.text();if(Buffer.byteLength(text)>2000000)throw new AiError("AI input exceeds 2 MB.",413);const b=JSON.parse(text),action=z.string().parse(b.action);await aiIndexes();const str=(k:string)=>z.string().min(1).max(100).parse(b[k]);if(action==="attach")return json(await service.attachPages(id,b.document,str("tenderId"),str("version")));if(action==="extract")return json(await service.extractChunk(id,str("documentId"),z.array(z.number().int().positive()).min(1).max(30).parse(b.pages),z.number().int().min(0).max(11).parse(b.chunkIndex)));if(action==="eligibility.requirement")return json(await service.reviewRequirement(id,str("tenderId"),str("requirementId"),z.number().int().min(0).parse(b.revision),str("requirementHash"),b.value));if(action==="eligibility")return json(await service.reviewEligibility(id,str("tenderId")));throw new AiError("Unknown AI action.");}catch(e){return failure(e);}}
