import {z} from "zod";
import {getAuth} from "@/lib/auth";
import {getDb} from "@/lib/db";
import {companySchema} from "@/lib/schemas";
import {AiError,aiConfig,aiIndexes,testMode} from "@/lib/ai/runtime";
import {PROMPT_VERSION} from "@/lib/ai/contracts";
import {hash} from "@/lib/ai/grounding";
import * as service from "@/lib/ai/service";
export const runtime="nodejs";
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"private, no-store"}});
async function owner(req:Request){const s=await getAuth().api.getSession({headers:req.headers});if(!s)throw new AiError("Please sign in again.",401);return s.user.id;}
function failure(e:unknown){if(e instanceof AiError)return json({error:e.message},e.status);if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:"Invalid AI request or response. Review your selected inputs."},400);const msg=e instanceof Error?e.message:"";if(msg==="NOT_FOUND")return json({error:"Record not found"},404);console.error("BidDesk AI request failed:",e instanceof Error?e.name:"Error");return json({error:"The operation failed. Check source availability and database connectivity, or use manual review."},503);}
export async function GET(req:Request){try{const id=await owner(req),p=new URL(req.url).searchParams;await aiIndexes();if(p.get("tenderId")){const state=await service.state(id,p.get("tenderId")!);return json({...state,documents:state.documents.map(d=>({...d,pages:d.pages.map(page=>({...page,text:""}))}))});}const db=await getDb(),company=companySchema.parse(await db.collection("companies").findOne({ownerId:id})||{});const saved=await db.collection("aiMatches").findOne({ownerId:id});const c=await service.candidates(id);const savedCandidates=await service.candidates(id,saved?.filters||{});const stale=!!saved&&(saved.candidateHash!==service.candidateHash(savedCandidates.items)||saved.promptVersion!==PROMPT_VERSION||saved.profileHash!==hash(company.aiProfile)||saved.model!==aiConfig().embeddingModel||saved.items.some((t:{id:string;hash:string;version:string})=>!c.items.some(v=>v.id===t.id&&v.hash===t.hash&&v.version===t.version)));return json({config:{...aiConfig(),configured:aiConfig().configured||testMode()},candidates:c.items.map(({id,title})=>({id,title})),coverage:{visible:c.total,described:c.items.length},matches:saved?{...saved,stale}:null});}catch(e){return failure(e);}}
export async function POST(req:Request){try{const origin=req.headers.get("origin");if(origin&&origin!==new URL(req.url).origin&&origin!==process.env.BETTER_AUTH_URL)throw new AiError("Invalid request origin.",403);if(Number(req.headers.get("content-length"))>2000000)throw new AiError("AI input exceeds 2 MB.",413);const id=await owner(req),text=await req.text();if(Buffer.byteLength(text)>2000000)throw new AiError("AI input exceeds 2 MB.",413);const b=JSON.parse(text),action=z.string().parse(b.action);await aiIndexes();const str=(k:string)=>z.string().min(1).max(100).parse(b[k]);if(action==="retrieve")return json(await service.retrieveDocument(id,str("tenderId"),str("version"),str("documentKey"),b.recheck===true));if(action==="attach")return json(await service.attachPages(id,b.document,b.tenderId?str("tenderId"):"",b.version?str("version"):""));if(action==="apply")return json(await service.applyDraft(id,b));if(action==="judgment")return json(await service.saveJudgment(id,b));if(action==="profile")return json(await service.publishPrivateProfile(id,str("tenderId")));service.consent(b.consent);if(action==="extract")return json(await service.extractChunk(id,str("documentId"),z.array(z.number().int().positive()).min(1).max(30).parse(b.pages),z.number().int().min(0).max(11).parse(b.chunkIndex)));if(action==="eligibility")return json(await service.reviewEligibility(id,str("tenderId")));if(action==="embed")return json(await service.prepareEmbedding(id,str("tenderId")));if(action==="matches")return json(await service.match(id,z.object({state:z.string().max(100).optional(),category:z.string().max(100).optional(),min:z.number().nonnegative().optional(),max:z.number().nonnegative().optional()}).parse(b.filters||{}),b.explain===true));throw new AiError("Unknown AI action.");}catch(e){return failure(e);}}
